import type { Config } from "tailwindcss";
import { fontFamily } from "tailwindcss/defaultTheme";

import baseTailwindConfig from "./base-tailwind.config";

const config: Config = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}", "./node_modules/@povio/ui/dist/**/*.js"],
  presets: [baseTailwindConfig],
  theme: {
    extend: {
      colors: {
        "support-default": "#000000",
        "support-inverted": "#ffffff",
        "interactive-outlined-primary-idle": "#ffffff00",
        "interactive-outlined-primary-disabled": "#ffffff00",
        "interactive-outlined-secondary-idle": "#ffffff00",
        "interactive-outlined-secondary-disabled": "#ffffff00",
        "interactive-outlined-success-idle": "#ffffff00",
        "interactive-outlined-success-disabled": "#ffffff00",
        "interactive-outlined-warning-idle": "#ffffff00",
        "interactive-outlined-warning-disabled": "#ffffff00",
        "interactive-outlined-error-idle": "#ffffff00",
        "interactive-outlined-error-disabled": "#ffffff00",
        "support-overlay": "#00000066",
        "elevation-fill-default-1": "#ffffff",
        "elevation-fill-default-2": "#13171d",
        "elevation-outline-default-1": "#dadde2",
        "elevation-outline-default-2": "#535963",
        "interactive-contained-primary-on-idle": "#ffffff",
        "interactive-contained-primary-idle": "#2b51d4",
        "interactive-contained-primary-hover": "#477fea",
        "interactive-contained-primary-disabled": "#9ac2f6",
        "interactive-contained-primary-focus": "#6aa1f0",
        "interactive-contained-secondary-on-idle": "#ffffff",
        "interactive-contained-secondary-idle": "#181c23",
        "interactive-contained-secondary-hover": "#535963",
        "interactive-contained-secondary-disabled": "#a2a9b4",
        "interactive-contained-secondary-focus": "#181c23",
        "interactive-outlined-primary-on-idle": "#2b51d4",
        "interactive-outlined-primary-outline-idle": "#2b51d4",
        "interactive-outlined-primary-outline-hover": "#477fea",
        "interactive-outlined-primary-outline-disabled": "#a2a9b4",
        "interactive-outlined-primary-focus": "#6aa1f0",
        "text-default-1": "#edeef1",
        "text-default-2": "#535963",
        "text-inverted-1": "#edeef1",
        "text-inverted-2": "#535963",
        "text-default-3": "#878f9b",
        "text-inverted-3": "#878f9b",
        "interactive-contained-primary-pressed": "#6aa1f0",
        "interactive-contained-secondary-pressed": "#535963",
        "interactive-outlined-primary-outline-pressed": "#6aa1f0",
        "elevation-fill-default-3": "#edeef1",
        "input-outlined-idle": "#13171d",
        "input-outlined-active": "#ffffff",
        "input-filled-idle": "#edeef1",
        "input-filled-active": "#ffffff",
        "input-outlined-hover": "#ffffff",
        "input-outlined-error": "#ffffff",
        "input-outlined-disabled": "#ffffff",
        "input-filled-hover": "#edeef1",
        "input-filled-error": "#edeef1",
        "input-filled-disabled": "#edeef1",
        "interactive-contained-success-on-idle": "#ffffff",
        "interactive-contained-success-idle": "#15803c",
        "interactive-contained-success-hover": "#16a34a",
        "interactive-contained-success-pressed": "#22c55e",
        "interactive-contained-success-disabled": "#15803c",
        "interactive-contained-success-focus": "#181c23",
        "interactive-contained-warning-on-idle": "#ffffff",
        "interactive-contained-warning-idle": "#d97706",
        "interactive-contained-warning-hover": "#f5880b",
        "interactive-contained-warning-pressed": "#fb9724",
        "interactive-contained-warning-disabled": "#b46509",
        "interactive-contained-warning-focus": "#181c23",
        "interactive-contained-error-on-idle": "#ffffff",
        "interactive-contained-error-idle": "#d43f2b",
        "interactive-contained-error-hover": "#e85e4b",
        "interactive-contained-error-pressed": "#f28677",
        "interactive-contained-error-disabled": "#b33322",
        "interactive-contained-error-focus": "#181c23",
        "interactive-outlined-secondary-on-idle": "#535963",
        "interactive-outlined-secondary-outline-idle": "#535963",
        "interactive-outlined-secondary-outline-hover": "#878f9b",
        "interactive-outlined-secondary-outline-pressed": "#181c23",
        "interactive-outlined-secondary-outline-disabled": "#181c23",
        "interactive-outlined-secondary-focus": "#181c23",
        "interactive-outlined-success-on-idle": "#16a34a",
        "interactive-outlined-success-outline-idle": "#16a34a",
        "interactive-outlined-success-outline-hover": "#22c55e",
        "interactive-outlined-success-outline-pressed": "#4ade81",
        "interactive-outlined-success-outline-disabled": "#a2a9b4",
        "interactive-outlined-success-focus": "#181c23",
        "interactive-outlined-warning-on-idle": "#f5880b",
        "interactive-outlined-warning-outline-idle": "#f5880b",
        "interactive-outlined-warning-outline-hover": "#fb9724",
        "interactive-outlined-warning-outline-pressed": "#fcab4d",
        "interactive-outlined-warning-outline-disabled": "#a2a9b4",
        "interactive-outlined-warning-focus": "#181c23",
        "interactive-outlined-error-on-idle": "#d43f2b",
        "interactive-outlined-error-outline-idle": "#d43f2b",
        "interactive-outlined-error-outline-hover": "#e85e4b",
        "interactive-outlined-error-outline-pressed": "#f28677",
        "interactive-outlined-error-outline-disabled": "#a2a9b4",
        "interactive-outlined-error-focus": "#181c23",
        "interactive-subtle-primary-on-idle": "#9ac2f6",
        "interactive-subtle-primary-idle": "#f0f5fe",
        "interactive-subtle-primary-hover": "#dde9fc",
        "interactive-subtle-primary-pressed": "#c3d9fa",
        "interactive-subtle-primary-disabled": "#f0f5fe",
        "interactive-subtle-primary-focus": "#6aa1f0",
        "interactive-subtle-secondary-on-idle": "#edeef1",
        "interactive-subtle-secondary-idle": "#13171d",
        "interactive-subtle-secondary-hover": "#dadde2",
        "interactive-subtle-secondary-pressed": "#6b737e",
        "interactive-subtle-secondary-disabled": "#13171d",
        "interactive-subtle-secondary-focus": "#181c23",
        "interactive-subtle-success-on-idle": "#86efad",
        "interactive-subtle-success-idle": "#dcfce8",
        "interactive-subtle-success-hover": "#bbf7d1",
        "interactive-subtle-success-pressed": "#86efad",
        "interactive-subtle-success-disabled": "#dcfce8",
        "interactive-subtle-success-focus": "#181c23",
        "interactive-subtle-warning-on-idle": "#fcab4d",
        "interactive-subtle-warning-idle": "#fee4c7",
        "interactive-subtle-warning-hover": "#fdc88a",
        "interactive-subtle-warning-pressed": "#b46509",
        "interactive-subtle-warning-disabled": "#fee4c7",
        "interactive-subtle-warning-focus": "#181c23",
        "interactive-subtle-error-on-idle": "#f8b2a9",
        "interactive-subtle-error-idle": "#fde6e3",
        "interactive-subtle-error-hover": "#faccc5",
        "interactive-subtle-error-pressed": "#b33322",
        "interactive-subtle-error-disabled": "#fde6e3",
        "interactive-subtle-error-focus": "#181c23",
        "interactive-subtle-primary-on-disabled": "#9ac2f6",
        "interactive-subtle-secondary-on-disabled": "#c0c6cd",
        "interactive-subtle-success-on-disabled": "#4ade81",
        "interactive-subtle-warning-on-disabled": "#fcab4d",
        "interactive-subtle-error-on-disabled": "#f28677",
        "text-success-1": "#16a34a",
        "text-warning-1": "#f5880b",
        "text-error-1": "#d43f2b",
        "interactive-text-primary-idle": "#2b51d4",
        "interactive-text-primary-hover": "#477fea",
        "interactive-text-primary-pressed": "#6aa1f0",
        "interactive-text-primary-disabled": "#878f9b",
        "interactive-text-primary-idle-inverted": "#f6f7f8",
        "interactive-text-primary-hover-inverted": "#477fea",
        "interactive-text-primary-pressed-inverted": "#477fea",
        "interactive-text-secondary-idle": "#edeef1",
        "interactive-text-secondary-hover": "#535963",
        "interactive-text-secondary-pressed": "#878f9b",
        "interactive-text-secondary-disabled": "#878f9b",
        "interactive-text-secondary-idle-inverted": "#f6f7f8",
        "interactive-text-secondary-hover-inverted": "#dadde2",
        "interactive-text-secondary-pressed-inverted": "#c0c6cd",
        "interactive-text-success-idle": "#16a34a",
        "interactive-text-success-hover": "#22c55e",
        "interactive-text-success-pressed": "#4ade81",
        "interactive-text-success-disabled": "#878f9b",
        "interactive-text-success-idle-inverted": "#f0fdf5",
        "interactive-text-success-hover-inverted": "#bbf7d1",
        "interactive-text-success-pressed-inverted": "#4ade81",
        "interactive-text-warning-idle": "#d97706",
        "interactive-text-warning-hover": "#f5880b",
        "interactive-text-warning-pressed": "#fb9724",
        "interactive-text-warning-disabled": "#878f9b",
        "interactive-text-warning-idle-inverted": "#fff6eb",
        "interactive-text-warning-hover-inverted": "#fdc88a",
        "interactive-text-warning-pressed-inverted": "#fcab4d",
        "interactive-text-error-idle": "#d43f2b",
        "interactive-text-error-hover": "#e85e4b",
        "interactive-text-error-pressed": "#f28677",
        "interactive-text-error-disabled": "#878f9b",
        "interactive-text-error-idle-inverted": "#fef3f2",
        "interactive-text-error-hover-inverted": "#faccc5",
        "interactive-text-error-pressed-inverted": "#f8b2a9",
        "interactive-outlined-primary-hover": "#f0f5fe",
        "interactive-outlined-secondary-hover": "#f6f7f8",
        "interactive-outlined-success-hover": "#f0fdf5",
        "interactive-outlined-warning-hover": "#fff6eb",
        "interactive-outlined-error-hover": "#fef3f2",
        "elevation-outline-default-3": "#878f9b",
        "elevation-outline-inverted-1": "#dadde2",
        "elevation-outline-inverted-2": "#535963",
        "elevation-outline-inverted-3": "#6b737e",
        "elevation-outline-success-1": "#4ade81",
        "elevation-outline-warning-1": "#fcab4d",
        "elevation-outline-error-1": "#e85e4b",
        "elevation-fill-inverted-1": "#181c23",
        "elevation-fill-inverted-2": "#dadde2",
        "elevation-fill-inverted-3": "#535963",
        "elevation-fill-success-1": "#16a34a",
        "elevation-fill-warning-1": "#f5880b",
        "elevation-fill-error-1": "#d43f2b",
        "text-success-2": "#16a34a",
        "text-warning-2": "#fb9724",
        "text-error-2": "#e85e4b",
        "text-success-3": "#15803c",
        "text-warning-3": "#fb9724",
        "text-error-3": "#f28677",
        "interactive-contained-primary-on-hover": "#ffffff",
        "interactive-contained-primary-on-pressed": "#ffffff",
        "interactive-contained-primary-on-disabled": "#1b2550",
        "interactive-contained-secondary-on-hover": "#ffffff",
        "interactive-contained-secondary-on-pressed": "#ffffff",
        "interactive-contained-secondary-on-disabled": "#6b737e",
        "interactive-contained-success-on-hover": "#ffffff",
        "interactive-contained-success-on-pressed": "#ffffff",
        "interactive-contained-success-on-disabled": "#14532b",
        "interactive-contained-warning-on-hover": "#ffffff",
        "interactive-contained-warning-on-pressed": "#ffffff",
        "interactive-contained-warning-on-disabled": "#78470f",
        "interactive-contained-error-on-hover": "#ffffff",
        "interactive-contained-error-on-pressed": "#ffffff",
        "interactive-contained-error-on-disabled": "#7b2c21",
        "interactive-outlined-primary-on-hover": "#477fea",
        "interactive-outlined-primary-on-pressed": "#6aa1f0",
        "interactive-outlined-primary-on-disabled": "#a2a9b4",
        "interactive-outlined-secondary-on-hover": "#edeef1",
        "interactive-outlined-secondary-on-pressed": "#181c23",
        "interactive-outlined-secondary-on-disabled": "#a2a9b4",
        "interactive-outlined-success-on-hover": "#22c55e",
        "interactive-outlined-success-on-pressed": "#4ade81",
        "interactive-outlined-success-on-disabled": "#a2a9b4",
        "interactive-outlined-warning-on-hover": "#fb9724",
        "interactive-outlined-warning-on-pressed": "#fcab4d",
        "interactive-outlined-warning-on-disabled": "#a2a9b4",
        "interactive-outlined-error-on-hover": "#e85e4b",
        "interactive-outlined-error-on-pressed": "#f28677",
        "interactive-outlined-error-on-disabled": "#a2a9b4",
        "interactive-subtle-primary-toggled-idle": "#dde9fc",
        "interactive-subtle-primary-on-hover": "#9ac2f6",
        "interactive-subtle-primary-on-pressed": "#9ac2f6",
        "interactive-subtle-primary-on-toggled-idle": "#2b51d4",
        "interactive-subtle-secondary-toggled-idle": "#181c23",
        "interactive-subtle-secondary-on-hover": "#252930",
        "interactive-subtle-secondary-on-pressed": "#252930",
        "interactive-subtle-secondary-on-toggled-idle": "#edeef1",
        "interactive-subtle-success-on-hover": "#166533",
        "interactive-subtle-success-on-pressed": "#166533",
        "interactive-subtle-warning-on-hover": "#92550e",
        "interactive-subtle-warning-on-pressed": "#92550e",
        "interactive-subtle-error-on-hover": "#942e20",
        "interactive-subtle-error-on-pressed": "#942e20",
        "interactive-outlined-primary-on-toggled-idle": "#ffffff",
        "interactive-outlined-primary-on-toggled-hover": "#ffffff",
        "interactive-outlined-primary-on-toggled-disabled": "#1b2550",
        "interactive-outlined-primary-toggled-idle": "#2b51d4",
        "interactive-outlined-primary-toggled-hover": "#477fea",
        "interactive-outlined-primary-toggled-disabled": "#a2a9b4",
        "interactive-outlined-primary-pressed": "#f0f5fe",
        "interactive-outlined-secondary-pressed": "#f6f7f8",
        "interactive-outlined-secondary-on-toggled-idle": "#ffffff",
        "interactive-outlined-secondary-on-toggled-hover": "#ffffff",
        "interactive-outlined-secondary-on-toggled-disabled": "#ffffff",
        "interactive-outlined-secondary-toggled-idle": "#181c23",
        "interactive-outlined-secondary-toggled-hover": "#878f9b",
        "interactive-outlined-secondary-toggled-disabled": "#a2a9b4",
        "interactive-outlined-success-pressed": "#f0fdf5",
        "interactive-outlined-warning-pressed": "#fff6eb",
        "interactive-outlined-error-pressed": "#fef3f2",
        "elevation-fill-inverted-4": "#6b737e",
        "interactive-text-primary-focus": "#6aa1f0",
        "interactive-text-secondary-focus": "#181c23",
        "interactive-text-secondary-focus-inverted": "#dadde2",
        "interactive-text-primary-focus-inverted": "#c3d9fa",
        "interactive-text-success-focus": "#181c23",
        "interactive-text-success-focus-inverted": "#dadde2",
        "interactive-text-warning-focus": "#181c23",
        "interactive-text-warning-focus-inverted": "#dadde2",
        "interactive-text-error-focus": "#181c23",
        "interactive-text-error-focus-inverted": "#dadde2",
        "interactive-subtle-secondary-on-toggled-hover": "#252930",
        "interactive-subtle-secondary-on-toggled-disabled": "#a2a9b4",
        "interactive-subtle-secondary-toggled-hover": "#181c23",
        "interactive-subtle-secondary-toggled-disabled": "#13171d",
        "interactive-text-primary-disabled-inverted": "#878f9b",
        "interactive-text-secondary-disabled-inverted": "#878f9b",
        "interactive-text-success-disabled-inverted": "#15803c",
        "interactive-text-warning-disabled-inverted": "#d97706",
        "interactive-text-error-disabled-inverted": "#b33322",
        "interactive-subtle-primary-on-toggled-hover": "#c3d9fa",
        "interactive-subtle-primary-on-toggled-disabled": "#a2a9b4",
        "interactive-subtle-primary-toggled-hover": "#c3d9fa",
        "interactive-subtle-primary-toggled-disabled": "#dde9fc",
        "input-outlined-outline-idle": "#181c23",
        "input-outlined-outline-hover": "#477fea",
        "input-outlined-outline-active": "#2b51d4",
        "input-outlined-outline-error": "#e85e4b",
        "input-outlined-outline-disabled": "#535963",
        "input-filled-outline-error": "#e85e4b",
        "input-filled-outline-hover": "#a2a9b4",
        "input-filled-outline-active": "#2b51d4",
        "interactive-contained-primary-on-toggled-disabled": "#a2a9b4",
        "interactive-contained-primary-on-toggled-idle": "#ffffff",
        "interactive-contained-primary-toggled-disabled": "#2840a5",
        "interactive-contained-primary-toggled-idle": "#2840a5",
        "interactive-contained-secondary-on-toggled-disabled": "#535963",
        "interactive-contained-secondary-on-toggled-idle": "#ffffff",
        "interactive-contained-secondary-toggled-disabled": "#13171d",
        "interactive-contained-secondary-toggled-idle": "#13171d",
        "interactive-contained-success-on-toggled-disabled": "#c0c6cd",
        "interactive-contained-success-on-toggled-idle": "#ffffff",
        "interactive-contained-success-toggled-disabled": "#15803c",
        "interactive-contained-success-toggled-idle": "#15803c",
        "interactive-contained-warning-on-toggled-idle": "#ffffff",
        "interactive-contained-warning-toggled-disabled": "#d97706",
        "interactive-contained-warning-on-toggled-disabled": "#dadde2",
        "interactive-contained-warning-toggled-idle": "#d97706",
        "interactive-contained-error-toggled-disabled": "#b33322",
        "interactive-contained-error-on-toggled-disabled": "#a2a9b4",
        "interactive-contained-error-on-toggled-idle": "#ffffff",
        "interactive-contained-error-toggled-idle": "#b33322",
        "interactive-subtle-success-toggled-disabled": "#bbf7d1",
        "interactive-subtle-success-on-toggled-disabled": "#a2a9b4",
        "interactive-subtle-success-on-toggled-idle": "#86efad",
        "interactive-subtle-success-toggled-idle": "#bbf7d1",
        "interactive-subtle-warning-on-toggled-idle": "#fcab4d",
        "interactive-subtle-warning-toggled-disabled": "#452603",
        "interactive-subtle-warning-toggled-idle": "#fee4c7",
        "interactive-subtle-warning-on-toggled-disabled": "#878f9b",
        "interactive-subtle-error-toggled-idle": "#faccc5",
        "interactive-subtle-error-on-toggled-disabled": "#878f9b",
        "interactive-subtle-error-toggled-disabled": "#43130c",
        "interactive-subtle-error-on-toggled-idle": "#f8b2a9",
        "interactive-contained-primary-toggled-hovered": "#477fea",
        "interactive-contained-primary-on-toggled-hovered": "#f6f7f8",
        "interactive-contained-secondary-toggled-hovered": "#181c23",
        "interactive-contained-secondary-on-toggled-hovered": "#f6f7f8",
        "interactive-contained-success-toggled-hovered": "#166533",
        "interactive-contained-success-on-toggled-hovered": "#f6f7f8",
        "interactive-subtle-success-toggled-hovered": "#4ade81",
        "interactive-subtle-success-on-toggled-hovered": "#86efad",
        "interactive-contained-warning-toggled-hovered": "#b46509",
        "interactive-contained-warning-on-toggled-hovered": "#f6f7f8",
        "interactive-subtle-warning-toggled-hovered": "#fcab4d",
        "interactive-subtle-warning-on-toggled-hovered": "#fcab4d",
        "interactive-contained-error-toggled-hovered": "#b33322",
        "interactive-contained-error-on-toggled-hovered": "#f6f7f8",
        "interactive-subtle-error-on-toggled-hovered": "#f8b2a9",
        "interactive-subtle-error-toggled-hovered": "#f28677",
      },
      borderRadius: {
        none: "0rem",
        "2xs": "0.125rem",
        xs: "0.25rem",
        s: "0.375rem",
        sm: "0.5rem",
        ml: "0.75rem",
        xl: "1rem",
        "4xl": "1.5rem",
        full: "624.9375rem",
        "5xl": "1.75rem",
        "6xl": "2rem",
        m: "0.625rem",
        l: "0.875rem",
        "2xl": "1.125rem",
        "3xl": "1.25rem",
        "global-rounding-xs": "0.25rem",
        "global-rounding-s": "0.375rem",
        "global-rounding-m": "0.5rem",
        "global-rounding-l": "0.625rem",
        "global-rounding-xl": "0.75rem",
        "input-rounding-default": "0.375rem",
        "list-rounding-actions": "0rem",
        "list-rounding-drawer": "1rem",
        "modal-rounding-default": "0.75rem",
        "toast-rounding-default": "0.5rem",
        "tooltip-rounding-default": "0.5rem",
        "button-rounding-m": "0.375rem",
        "alert-rounding-default": "0.5rem",
        "pill-rounding-default": "0.375rem",
        "button-focus-rounding-m": "0.5rem",
        "list-rounding-dropdown": "0.375rem",
        "button-rounding-s": "0.25rem",
        "button-rounding-xs": "0.125rem",
        "button-rounding-l": "0.5rem",
        "button-rounding-xl": "0.625rem",
        "button-focus-rounding-s": "0.375rem",
        "button-focus-rounding-l": "0.625rem",
        "button-focus-rounding-xl": "0.75rem",
        "file-upload-container-rounding-default": "0.375rem",
        "file-upload-file-card-rounding-default": "0.375rem",
        "image-upload-container-clipping-layer-default": "0rem",
        "segmented-control-rounding-segment": "0.375rem",
        "image-upload-avatar-with-buttons-rounding-default": "624.9375rem",
        "image-overlay-inside-rounding-full": "624.9375rem",
        "segmented-control-rounding-segmented-control": "0.5rem",
        "image-overlay-outside-rounding-full": "624.9375rem",
        "avatar-rounding-default": "624.9375rem",
        "progress-rounding-default": "0.25rem",
        "slider-rounding-default": "0.25rem",
      },
      maxWidth: {
        "0": "0rem",
        "1": "0.25rem",
        "2": "0.5rem",
        "3": "0.75rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "7": "1.75rem",
        "8": "2rem",
        "9": "2.25rem",
        "10": "2.5rem",
        "11": "2.75rem",
        "12": "3rem",
        "14": "3.5rem",
        "16": "4rem",
        "18": "4.5rem",
        "20": "5rem",
        "24": "6rem",
        "28": "7rem",
        "32": "8rem",
        "36": "9rem",
        "40": "10rem",
        "44": "11rem",
        "48": "12rem",
        "52": "13rem",
        "56": "14rem",
        "60": "15rem",
        "64": "16rem",
        "72": "18rem",
        "80": "20rem",
        "96": "24rem",
        xs: "20rem",
        sm: "24rem",
        md: "28rem",
        lg: "32rem",
        xl: "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "7xl": "80rem",
        "2xs": "16rem",
        "3xs": "12rem",
        "3-5xs": "9.75rem",
        "4xs": "8rem",
        "4-5xs": "7rem",
        "5-5xs": "4.75rem",
        "5xs": "6rem",
        px: "0.0625rem",
        "0-5": "0.125rem",
        "1-5": "0.375rem",
        "2-5": "0.625rem",
        "3-5": "0.875rem",
        "avatar-height-xs": "1.5rem",
        "avatar-height-s": "2rem",
        "avatar-height-m": "2.5rem",
        "avatar-height-l": "3.5rem",
        "avatar-height-xl": "4.5rem",
        "avatar-height-xxl": "6rem",
        "button-width-min-width-xxs": "1.625rem",
        "button-width-min-width-xs": "1.875rem",
        "button-width-min-width-s": "2.125rem",
        "button-width-min-width-m": "2.875rem",
        "button-width-min-width-l": "3.625rem",
        "fill-outer": "NaNrem",
        "global-side-xs": "0.125rem",
        "global-side-s": "0.25rem",
        "global-side-m": "0.625rem",
        "global-side-l": "1rem",
        "global-side-xl": "1.25rem",
        "global-gap-xs": "0.25rem",
        "global-gap-s": "0.5rem",
        "global-gap-m": "0.75rem",
        "global-gap-l": "1rem",
        "global-gap-xl": "1.25rem",
        "global-gap-ml": "0.875rem",
        "global-gap-sm": "0.625rem",
        "global-side-sm": "0.375rem",
        "global-side-ml": "0.75rem",
        "global-height-xs": "0.125rem",
        "global-height-s": "0.25rem",
        "global-height-m": "0.625rem",
        "global-height-l": "0.875rem",
        "global-height-xl": "1rem",
        "button-height-s": "0.25rem",
        "button-height-m": "0.625rem",
        "button-height-l": "1rem",
        "button-side-s": "0.25rem",
        "button-side-m": "1rem",
        "button-side-l": "1.75rem",
        "list-gap-icon-to-label": "0.25rem",
        "input-height-extra-small": "0.125rem",
        "input-side-l": "0.75rem",
        "input-gap-label-to-input": "0.25rem",
        "input-gap-text-area-controls": "0.5rem",
        "list-height-item": "0.5rem",
        "list-height-actions": "0.25rem",
        "list-height-title-top": "0.75rem",
        "list-side-item": "1rem",
        "list-side-actions": "1rem",
        "list-height-bottom": "8rem",
        "list-gap-checkbox-to-label": "0.5rem",
        "list-gap-label-to-subcontent": "0.0625rem",
        "list-side-extra-actions": "1.5rem",
        "list-height-extra-actions": "1.5rem",
        "modal-side-desktop": "2.5rem",
        "modal-height-desktop": "2.5rem",
        "modal-gap-buttons": "1rem",
        "modal-gap-text": "0.625rem",
        "modal-gap-content": "1.75rem",
        "modal-gap-form": "2rem",
        "toast-height-content": "0.875rem",
        "toast-side-default": "1rem",
        "toast-gap-action": "1rem",
        "tooltip-height-default": "0.5rem",
        "tooltip-side-default": "0.75rem",
        "table-cell-content-gap-s": "0.25rem",
        "table-cell-content-gap-m": "0.375rem",
        "table-cell-content-gap-l": "0.5rem",
        "table-cell-content-height-s": "0.25rem",
        "table-cell-content-height-m": "0.25rem",
        "table-cell-content-side-s": "0.375rem",
        "table-cell-content-side-m": "0.5rem",
        "table-cell-container-height-default": "0.5rem",
        "table-cell-container-side-default": "0.5rem",
        "table-header-cell-container-height-default": "0.5rem",
        "table-header-cell-container-side-default": "0.5rem",
        "toast-height-actions-mobile": "0.5rem",
        "toast-gap-icon-to-text": "0.75rem",
        "alert-height-content": "0.875rem",
        "alert-height-actions-mobile": "0.5rem",
        "alert-side-default": "1rem",
        "alert-gap-icon-to-text": "0.75rem",
        "alert-gap-action": "1rem",
        "slider-side-bar": "0rem",
        "slider-height-bar": "0.625rem",
        "input-gap-error-to-input": "0.375rem",
        "list-side-title": "1rem",
        "list-gap-title-to-icon": "0.125rem",
        "list-gap-title-to-helper-text": "0rem",
        "list-height-title-bottom": "0.375rem",
        "toast-height-actions-desktop": "0.75rem",
        "alert-height-actions-desktop": "0.75rem",
        "tooltip-gap-margin": "0.75rem",
        "list-gap-margin": "1rem",
        "modal-gap-buttons-top": "0.25rem",
        "list-height-subcontent-bottom": "0.25rem",
        "pill-side-default": "0.5rem",
        "pill-height-default": "0.125rem",
        "button-focus-rounding-xs": "0.125rem",
        "modal-side-mobile": "1rem",
        "modal-height-mobile": "1rem",
        "pill-gap-pill-to-pill": "0.5rem",
        "progress-side-bar": "0.5rem",
        "progress-height-bar": "0.25rem",
        "file-upload-container-height-top-bottom": "1.5rem",
        "file-upload-container-side-default": "1.5rem",
        "file-upload-file-card-height-top-bottom": "1rem",
        "file-upload-file-card-side-default": "1rem",
        "file-upload-content-height-xs": "0.25rem",
        "file-upload-content-height-s": "0.5rem",
        "file-upload-content-height-m": "1rem",
        "file-upload-content-height-l": "1.75rem",
        "file-upload-content-height-xl": "2rem",
        "input-gap-trailing-elements": "0.25rem",
        "toast-gap-margin-desktop": "2rem",
        "toast-gap-margin-mobile": "1rem",
        "list-gap-content": "0.375rem",
        "floating-label-input-height-empty": "1rem",
        "floating-label-input-height-filled": "0.5rem",
        "floating-label-input-gap-label-to-input": "0.25rem",
        "floating-label-input-gap-trailing-elements": "0.25rem",
        "floating-label-input-gap-error-to-input": "0.375rem",
        "file-upload-content-gap-icon-to-content": "0.5rem",
        "file-upload-content-gap-text-to-text": "0.25rem",
        "file-upload-content-gap-content-to-button": "1.25rem",
        "file-upload-content-gap-text-to-progress": "0.25rem",
        "file-upload-content-gap-progress-actions": "0.5rem",
        "file-upload-content-gap-left-to-right-content": "1rem",
        "file-upload-content-gap-button-to-button": "1rem",
        "file-upload-file-card-gap-icon-to-content-gap": "0.5rem",
        "file-upload-file-card-gap-text-to-text-gap": "0.25rem",
        "file-upload-file-card-gap-progress-actions-gap": "0.5rem",
        "file-upload-file-card-gap-left-to-right-content-gap": "1rem",
        "file-upload-file-card-gap-trailing-actions": "0.5rem",
        "file-upload-input-gap-input-to-button-gap": "0.625rem",
        "image-upload-content-gap-icon-to-content-gap": "0.5rem",
        "image-upload-avatar-with-buttons-height-top-bottom": "0rem",
        "image-upload-avatar-with-buttons-side-default": "0rem",
        "image-upload-avatar-with-buttons-gap-avatar-to-content-gap": "1.25rem",
        "image-upload-avatar-with-buttons-gap-text-to-text-gap": "0.25rem",
        "image-upload-avatar-with-buttons-gap-text-to-buttons-gap": "1.25rem",
        "image-upload-avatar-with-buttons-gap-actions-gap": "1rem",
        "segmented-control-height-segment": "0.25rem",
        "segmented-control-side-segment": "0.75rem",
        "segmented-control-gap-content-icon-to-text": "0.25rem",
        "segmented-control-gap-segment-to-segment": "0.125rem",
        "image-overlay-inside-rounding-none": "0rem",
        "image-overlay-inside-rounding-rounded": "1rem",
        "segmented-control-side-content": "0.375rem",
        "segmented-control-side-segmented-control": "0.125rem",
        "image-overlay-outside-rounding-none": "0rem",
        "image-overlay-outside-rounding-rounded": "1rem",
        "input-gap-leading-elements": "0.375rem",
        "image-upload-avatar-with-buttons-gap-icon-button-right-bottom": "0rem",
        "image-upload-container-gap-icon-button-right-bottom": "0rem",
        "modal-gap-desktop-modal-close-icon-top-right": "0.25rem",
        "modal-gap-mobile-modal-close-icon-top-right": "0rem",
        "modal-gap-close-icon-container": "0.5rem",
        "list-gap-nav-button-icon-to-label": "0.125rem",
        "list-gap-footer-button-icon-to-label": "0.125rem",
        "button-height-xs": "0.125rem",
        "button-side-xs": "0.125rem",
        "input-gap-header-text-to-elements": "0.125rem",
        "floating-label-input-gap-header-text-to-elements": "0.125rem",
        "floating-label-input-gap-leading-elements": "0.375rem",
        "input-gap-input-text-to-elements": "0.5rem",
        "input-gap-text-to-text": "0.25rem",
        "avatar-padding-xs": "0.25rem",
        "avatar-padding-s": "0.5rem",
        "avatar-padding-m": "0.625rem",
        "avatar-padding-l": "1rem",
        "avatar-padding-xl": "1.25rem",
        "avatar-padding-xxl": "1.75rem",
        "progress-height-leading-and-trailing": "0.25rem",
        "progress-side-leading-and-trailing": "0.5rem",
        "slider-height-leading-and-trailing": "0.625rem",
        "slider-side-leading-and-trailing": "0rem",
        "button-height-none": "0rem",
        "button-side-none": "0rem",
        "button-rounding-none": "0rem",
        "input-height-small": "0.25rem",
        "input-height-default": "0.625rem",
        "input-height-large": "1rem",
        "pagination-button-to-button": "0.5rem",
        "button-button-content-side-none": "0rem",
        "button-button-content-side-default": "0.375rem",
        "button-button-content-height-none": "0rem",
        "button-side-sm": "0.5rem",
        "button-side-ml": "1rem",
        "input-side-xs": "0.25rem",
        "input-side-s": "0.375rem",
        "input-side-m": "0.625rem",
        "button-side-xxs": "0.125rem",
        "button-segment-control-buttonside-xs": "0.875rem",
        "button-segment-control-buttonside-s": "1.25rem",
        "button-segment-control-buttonside-m": "2rem",
        "button-segment-control-buttonside-l": "4rem",
        "button-segment-control-segment-side-xs": "0.125rem",
        "button-segment-control-segment-side-s": "0.25rem",
        "button-segment-control-segment-side-m": "0.375rem",
        "button-segment-control-segment-side-l": "0.375rem",
        "button-segment-control-segment-height-xs": "0.125rem",
        "button-segment-control-segment-height-s": "0.25rem",
        "button-segment-control-segment-height-m": "0.375rem",
        "button-segment-control-segment-height-l": "0.375rem",
        "button-gap-icon-to-label": "0.25rem",
        "fill-inner": "NaNrem",
      },
      spacing: {
        "0": "0rem",
        "1": "0.25rem",
        "2": "0.5rem",
        "3": "0.75rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "7": "1.75rem",
        "8": "2rem",
        "9": "2.25rem",
        "10": "2.5rem",
        "11": "2.75rem",
        "12": "3rem",
        "14": "3.5rem",
        "16": "4rem",
        "18": "4.5rem",
        "20": "5rem",
        "24": "6rem",
        "28": "7rem",
        "32": "8rem",
        "36": "9rem",
        "40": "10rem",
        "44": "11rem",
        "48": "12rem",
        "52": "13rem",
        "56": "14rem",
        "60": "15rem",
        "64": "16rem",
        "72": "18rem",
        "80": "20rem",
        "96": "24rem",
        px: "0.0625rem",
        "0-5": "0.125rem",
        "1-5": "0.375rem",
        "2-5": "0.625rem",
        "3-5": "0.875rem",
        "avatar-height-xs": "1.5rem",
        "avatar-height-s": "2rem",
        "avatar-height-m": "2.5rem",
        "avatar-height-l": "3.5rem",
        "avatar-height-xl": "4.5rem",
        "avatar-height-xxl": "6rem",
        "button-width-min-width-xxs": "1.625rem",
        "button-width-min-width-xs": "1.875rem",
        "button-width-min-width-s": "2.125rem",
        "button-width-min-width-m": "2.875rem",
        "button-width-min-width-l": "3.625rem",
        "fill-outer": "NaNrem",
        "global-side-xs": "0.125rem",
        "global-side-s": "0.25rem",
        "global-side-m": "0.625rem",
        "global-side-l": "1rem",
        "global-side-xl": "1.25rem",
        "global-gap-xs": "0.25rem",
        "global-gap-s": "0.5rem",
        "global-gap-m": "0.75rem",
        "global-gap-l": "1rem",
        "global-gap-xl": "1.25rem",
        "global-gap-ml": "0.875rem",
        "global-gap-sm": "0.625rem",
        "global-side-sm": "0.375rem",
        "global-side-ml": "0.75rem",
        "global-height-xs": "0.125rem",
        "global-height-s": "0.25rem",
        "global-height-m": "0.625rem",
        "global-height-l": "0.875rem",
        "global-height-xl": "1rem",
        "button-height-s": "0.25rem",
        "button-height-m": "0.625rem",
        "button-height-l": "1rem",
        "button-side-s": "0.25rem",
        "button-side-m": "1rem",
        "button-side-l": "1.75rem",
        "list-gap-icon-to-label": "0.25rem",
        "input-height-extra-small": "0.125rem",
        "input-side-l": "0.75rem",
        "input-gap-label-to-input": "0.25rem",
        "input-gap-text-area-controls": "0.5rem",
        "list-height-item": "0.5rem",
        "list-height-actions": "0.25rem",
        "list-height-title-top": "0.75rem",
        "list-side-item": "1rem",
        "list-side-actions": "1rem",
        "list-height-bottom": "8rem",
        "list-gap-checkbox-to-label": "0.5rem",
        "list-gap-label-to-subcontent": "0.0625rem",
        "list-side-extra-actions": "1.5rem",
        "list-height-extra-actions": "1.5rem",
        "modal-side-desktop": "2.5rem",
        "modal-height-desktop": "2.5rem",
        "modal-gap-buttons": "1rem",
        "modal-gap-text": "0.625rem",
        "modal-gap-content": "1.75rem",
        "modal-gap-form": "2rem",
        "toast-height-content": "0.875rem",
        "toast-side-default": "1rem",
        "toast-gap-action": "1rem",
        "tooltip-height-default": "0.5rem",
        "tooltip-side-default": "0.75rem",
        "table-cell-content-gap-s": "0.25rem",
        "table-cell-content-gap-m": "0.375rem",
        "table-cell-content-gap-l": "0.5rem",
        "table-cell-content-height-s": "0.25rem",
        "table-cell-content-height-m": "0.25rem",
        "table-cell-content-side-s": "0.375rem",
        "table-cell-content-side-m": "0.5rem",
        "table-cell-container-height-default": "0.5rem",
        "table-cell-container-side-default": "0.5rem",
        "table-header-cell-container-height-default": "0.5rem",
        "table-header-cell-container-side-default": "0.5rem",
        "toast-height-actions-mobile": "0.5rem",
        "toast-gap-icon-to-text": "0.75rem",
        "alert-height-content": "0.875rem",
        "alert-height-actions-mobile": "0.5rem",
        "alert-side-default": "1rem",
        "alert-gap-icon-to-text": "0.75rem",
        "alert-gap-action": "1rem",
        "slider-side-bar": "0rem",
        "slider-height-bar": "0.625rem",
        "input-gap-error-to-input": "0.375rem",
        "list-side-title": "1rem",
        "list-gap-title-to-icon": "0.125rem",
        "list-gap-title-to-helper-text": "0rem",
        "list-height-title-bottom": "0.375rem",
        "toast-height-actions-desktop": "0.75rem",
        "alert-height-actions-desktop": "0.75rem",
        "tooltip-gap-margin": "0.75rem",
        "list-gap-margin": "1rem",
        "modal-gap-buttons-top": "0.25rem",
        "list-height-subcontent-bottom": "0.25rem",
        "pill-side-default": "0.5rem",
        "pill-height-default": "0.125rem",
        "button-focus-rounding-xs": "0.125rem",
        "modal-side-mobile": "1rem",
        "modal-height-mobile": "1rem",
        "pill-gap-pill-to-pill": "0.5rem",
        "progress-side-bar": "0.5rem",
        "progress-height-bar": "0.25rem",
        "file-upload-container-height-top-bottom": "1.5rem",
        "file-upload-container-side-default": "1.5rem",
        "file-upload-file-card-height-top-bottom": "1rem",
        "file-upload-file-card-side-default": "1rem",
        "file-upload-content-height-xs": "0.25rem",
        "file-upload-content-height-s": "0.5rem",
        "file-upload-content-height-m": "1rem",
        "file-upload-content-height-l": "1.75rem",
        "file-upload-content-height-xl": "2rem",
        "input-gap-trailing-elements": "0.25rem",
        "toast-gap-margin-desktop": "2rem",
        "toast-gap-margin-mobile": "1rem",
        "list-gap-content": "0.375rem",
        "floating-label-input-height-empty": "1rem",
        "floating-label-input-height-filled": "0.5rem",
        "floating-label-input-gap-label-to-input": "0.25rem",
        "floating-label-input-gap-trailing-elements": "0.25rem",
        "floating-label-input-gap-error-to-input": "0.375rem",
        "file-upload-content-gap-icon-to-content": "0.5rem",
        "file-upload-content-gap-text-to-text": "0.25rem",
        "file-upload-content-gap-content-to-button": "1.25rem",
        "file-upload-content-gap-text-to-progress": "0.25rem",
        "file-upload-content-gap-progress-actions": "0.5rem",
        "file-upload-content-gap-left-to-right-content": "1rem",
        "file-upload-content-gap-button-to-button": "1rem",
        "file-upload-file-card-gap-icon-to-content-gap": "0.5rem",
        "file-upload-file-card-gap-text-to-text-gap": "0.25rem",
        "file-upload-file-card-gap-progress-actions-gap": "0.5rem",
        "file-upload-file-card-gap-left-to-right-content-gap": "1rem",
        "file-upload-file-card-gap-trailing-actions": "0.5rem",
        "file-upload-input-gap-input-to-button-gap": "0.625rem",
        "image-upload-content-gap-icon-to-content-gap": "0.5rem",
        "image-upload-avatar-with-buttons-height-top-bottom": "0rem",
        "image-upload-avatar-with-buttons-side-default": "0rem",
        "image-upload-avatar-with-buttons-gap-avatar-to-content-gap": "1.25rem",
        "image-upload-avatar-with-buttons-gap-text-to-text-gap": "0.25rem",
        "image-upload-avatar-with-buttons-gap-text-to-buttons-gap": "1.25rem",
        "image-upload-avatar-with-buttons-gap-actions-gap": "1rem",
        "segmented-control-height-segment": "0.25rem",
        "segmented-control-side-segment": "0.75rem",
        "segmented-control-gap-content-icon-to-text": "0.25rem",
        "segmented-control-gap-segment-to-segment": "0.125rem",
        "image-overlay-inside-rounding-none": "0rem",
        "image-overlay-inside-rounding-rounded": "1rem",
        "segmented-control-side-content": "0.375rem",
        "segmented-control-side-segmented-control": "0.125rem",
        "image-overlay-outside-rounding-none": "0rem",
        "image-overlay-outside-rounding-rounded": "1rem",
        "input-gap-leading-elements": "0.375rem",
        "image-upload-avatar-with-buttons-gap-icon-button-right-bottom": "0rem",
        "image-upload-container-gap-icon-button-right-bottom": "0rem",
        "modal-gap-desktop-modal-close-icon-top-right": "0.25rem",
        "modal-gap-mobile-modal-close-icon-top-right": "0rem",
        "modal-gap-close-icon-container": "0.5rem",
        "list-gap-nav-button-icon-to-label": "0.125rem",
        "list-gap-footer-button-icon-to-label": "0.125rem",
        "button-height-xs": "0.125rem",
        "button-side-xs": "0.125rem",
        "input-gap-header-text-to-elements": "0.125rem",
        "floating-label-input-gap-header-text-to-elements": "0.125rem",
        "floating-label-input-gap-leading-elements": "0.375rem",
        "input-gap-input-text-to-elements": "0.5rem",
        "input-gap-text-to-text": "0.25rem",
        "avatar-padding-xs": "0.25rem",
        "avatar-padding-s": "0.5rem",
        "avatar-padding-m": "0.625rem",
        "avatar-padding-l": "1rem",
        "avatar-padding-xl": "1.25rem",
        "avatar-padding-xxl": "1.75rem",
        "progress-height-leading-and-trailing": "0.25rem",
        "progress-side-leading-and-trailing": "0.5rem",
        "slider-height-leading-and-trailing": "0.625rem",
        "slider-side-leading-and-trailing": "0rem",
        "button-height-none": "0rem",
        "button-side-none": "0rem",
        "button-rounding-none": "0rem",
        "input-height-small": "0.25rem",
        "input-height-default": "0.625rem",
        "input-height-large": "1rem",
        "pagination-button-to-button": "0.5rem",
        "button-button-content-side-none": "0rem",
        "button-button-content-side-default": "0.375rem",
        "button-button-content-height-none": "0rem",
        "button-side-sm": "0.5rem",
        "button-side-ml": "1rem",
        "input-side-xs": "0.25rem",
        "input-side-s": "0.375rem",
        "input-side-m": "0.625rem",
        "button-side-xxs": "0.125rem",
        "button-segment-control-buttonside-xs": "0.875rem",
        "button-segment-control-buttonside-s": "1.25rem",
        "button-segment-control-buttonside-m": "2rem",
        "button-segment-control-buttonside-l": "4rem",
        "button-segment-control-segment-side-xs": "0.125rem",
        "button-segment-control-segment-side-s": "0.25rem",
        "button-segment-control-segment-side-m": "0.375rem",
        "button-segment-control-segment-side-l": "0.375rem",
        "button-segment-control-segment-height-xs": "0.125rem",
        "button-segment-control-segment-height-s": "0.25rem",
        "button-segment-control-segment-height-m": "0.375rem",
        "button-segment-control-segment-height-l": "0.375rem",
        "button-gap-icon-to-label": "0.25rem",
        "fill-inner": "NaNrem",
      },
      boxShadow: {
        "1": "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
        "2": "0 1px 3px 0 rgba(0, 0, 0, 0.10), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
        "3": "0 4px 6px -1px rgba(0, 0, 0, 0.10), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
        "4": "0 10px 15px -3px rgba(0, 0, 0, 0.10), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
        "6": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
        ".text-shadow-dark-mode": "0 2px 6px 0 rgba(0, 0, 0, 0.30)",
        inner: "0 2px 4px 0 rgba(0, 0, 0, 0.06) inset",
      },
      blur: {
        "0": "0px",
        "1": "2px",
        "2": "4px",
        "3": "6px",
        "4": "8px",
        "5": "12px",
        "6": "20px",
        "7": "32px",
      },
      backdropBlur: {
        "1": "2px",
        "2": "4px",
        "3": "6px",
        "4": "8px",
        "5": "12px",
        "6": "20px",
        "7": "32px",
      },
      fontSize: {
        "desktop-headline-1": [
          "3.5rem",
          {
            lineHeight: "1.2857",
            letterSpacing: "0em",
          },
        ],
        "desktop-title-1": [
          "3rem",
          {
            lineHeight: "1.25",
            letterSpacing: "0em",
          },
        ],
        "desktop-title-2": [
          "2rem",
          {
            lineHeight: "1.3125",
            letterSpacing: "0em",
          },
        ],
        "desktop-title-3": [
          "1.75rem",
          {
            lineHeight: "1.3571",
            letterSpacing: "0em",
          },
        ],
        "desktop-title-4": [
          "1.375rem",
          {
            lineHeight: "1.2727",
            letterSpacing: "0em",
          },
        ],
        "desktop-title-5": [
          "1.125rem",
          {
            lineHeight: "1.4444",
            letterSpacing: "0em",
          },
        ],
        "desktop-title-6": [
          "1rem",
          {
            lineHeight: "1.5",
            letterSpacing: "0em",
          },
        ],
        "mobile-headline-1": [
          "2rem",
          {
            lineHeight: "1.1875",
            letterSpacing: "0em",
          },
        ],
        "mobile-title-1": [
          "1.75rem",
          {
            lineHeight: "1.2857",
            letterSpacing: "0em",
          },
        ],
        "mobile-title-2": [
          "1.5rem",
          {
            lineHeight: "1.3333",
            letterSpacing: "0em",
          },
        ],
        "mobile-title-3": [
          "1.125rem",
          {
            lineHeight: "1.4444",
            letterSpacing: "0em",
          },
        ],
        "mobile-title-4": [
          "1rem",
          {
            lineHeight: "1.5",
            letterSpacing: "0em",
          },
        ],
        "mobile-title-5": [
          "0.875rem",
          {
            lineHeight: "1.2857",
            letterSpacing: "0em",
          },
        ],
        "mobile-title-6": [
          "0.875rem",
          {
            lineHeight: "1.2857",
            letterSpacing: "0em",
          },
        ],
        "desktop-body-1": [
          "1.25rem",
          {
            lineHeight: "1.8",
            letterSpacing: "0em",
          },
        ],
        "desktop-body-2": [
          "1.125rem",
          {
            lineHeight: "1.7778",
            letterSpacing: "-0.0018em",
          },
        ],
        "desktop-body-3": [
          "1rem",
          {
            lineHeight: "1.75",
            letterSpacing: "-0.0016em",
          },
        ],
        "desktop-body-4": [
          "0.875rem",
          {
            lineHeight: "1.7143",
            letterSpacing: "-0.0014em",
          },
        ],
        "mobile-body-1": [
          "1.125rem",
          {
            lineHeight: "1.5556",
            letterSpacing: "0em",
          },
        ],
        "mobile-body-2": [
          "1rem",
          {
            lineHeight: "1.75",
            letterSpacing: "-0.0016em",
          },
        ],
        "mobile-body-3": [
          "0.9375rem",
          {
            lineHeight: "1.7333",
            letterSpacing: "-0.0015em",
          },
        ],
        "mobile-body-4": [
          "0.875rem",
          {
            lineHeight: "1.7143",
            letterSpacing: "-0.0014em",
          },
        ],
        "label-1": [
          "1rem",
          {
            lineHeight: "1.5",
            letterSpacing: "0em",
          },
        ],
        "label-2": [
          "0.875rem",
          {
            lineHeight: "1.7143",
            letterSpacing: "0em",
          },
        ],
        "label-3": [
          "0.75rem",
          {
            lineHeight: "1.3333",
            letterSpacing: "-0.0012em",
          },
        ],
      },
      fontFamily: {
        secondary: ["var(--font-geist)", ...fontFamily.sans],
        geist: ["var(--font-geist)", ...fontFamily.sans],
        primary: ["var(--font-inter)", ...fontFamily.sans],
        inter: ["var(--font-inter)", ...fontFamily.sans],
      },
      fontWeight: {
        "headings-default": "500",
        "headings-prominent-1": "600",
        "body-default": "400",
        "body-prominent-1": "500",
        "body-prominent-2": "600",
        "labels-default": "500",
        "labels-prominent-1": "600",
      },
      backgroundImage: {},
    },
  },
};

export default config;
