import type { Config } from "tailwindcss";
import { fontFamily } from "tailwindcss/defaultTheme";

import baseTailwindConfig from "./src/styles/tailwind-v3/base-tailwind.config";

const config: Config = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}", "./node_modules/@povio/ui/dist/**/*.js"],
  presets: [baseTailwindConfig],
  theme: {
    extend: {
      colors: {
        "support-default": "rgb(var(--support-default-base) / <alpha-value>)",
        "support-inverted": "rgb(var(--support-inverted-base) / <alpha-value>)",
        "interactive-outlined-primary-idle": "var(--interactive-outlined-primary-idle-base)",
        "interactive-outlined-primary-disabled": "var(--interactive-outlined-primary-disabled-base)",
        "interactive-outlined-secondary-idle": "var(--interactive-outlined-secondary-idle-base)",
        "interactive-outlined-secondary-disabled": "var(--interactive-outlined-secondary-disabled-base)",
        "interactive-outlined-success-idle": "var(--interactive-outlined-success-idle-base)",
        "interactive-outlined-success-disabled": "var(--interactive-outlined-success-disabled-base)",
        "interactive-outlined-warning-idle": "var(--interactive-outlined-warning-idle-base)",
        "interactive-outlined-warning-disabled": "var(--interactive-outlined-warning-disabled-base)",
        "interactive-outlined-error-idle": "var(--interactive-outlined-error-idle-base)",
        "interactive-outlined-error-disabled": "var(--interactive-outlined-error-disabled-base)",
        "support-overlay": "var(--support-overlay-base)",
        "elevation-fill-default-1": "rgb(var(--elevation-fill-default-1-base) / <alpha-value>)",
        "elevation-fill-default-2": "rgb(var(--elevation-fill-default-2-base) / <alpha-value>)",
        "elevation-outline-default-1": "rgb(var(--elevation-outline-default-1-base) / <alpha-value>)",
        "elevation-outline-default-2": "rgb(var(--elevation-outline-default-2-base) / <alpha-value>)",
        "interactive-contained-primary-on-idle":
          "rgb(var(--interactive-contained-primary-on-idle-base) / <alpha-value>)",
        "interactive-contained-primary-idle": "rgb(var(--interactive-contained-primary-idle-base) / <alpha-value>)",
        "interactive-contained-primary-hover": "rgb(var(--interactive-contained-primary-hover-base) / <alpha-value>)",
        "interactive-contained-primary-disabled":
          "rgb(var(--interactive-contained-primary-disabled-base) / <alpha-value>)",
        "interactive-contained-primary-focus": "rgb(var(--interactive-contained-primary-focus-base) / <alpha-value>)",
        "interactive-contained-secondary-on-idle":
          "rgb(var(--interactive-contained-secondary-on-idle-base) / <alpha-value>)",
        "interactive-contained-secondary-idle": "rgb(var(--interactive-contained-secondary-idle-base) / <alpha-value>)",
        "interactive-contained-secondary-hover":
          "rgb(var(--interactive-contained-secondary-hover-base) / <alpha-value>)",
        "interactive-contained-secondary-disabled":
          "rgb(var(--interactive-contained-secondary-disabled-base) / <alpha-value>)",
        "interactive-contained-secondary-focus":
          "rgb(var(--interactive-contained-secondary-focus-base) / <alpha-value>)",
        "interactive-outlined-primary-on-idle": "rgb(var(--interactive-outlined-primary-on-idle-base) / <alpha-value>)",
        "interactive-outlined-primary-outline-idle":
          "rgb(var(--interactive-outlined-primary-outline-idle-base) / <alpha-value>)",
        "interactive-outlined-primary-outline-hover":
          "rgb(var(--interactive-outlined-primary-outline-hover-base) / <alpha-value>)",
        "interactive-outlined-primary-outline-disabled":
          "rgb(var(--interactive-outlined-primary-outline-disabled-base) / <alpha-value>)",
        "interactive-outlined-primary-focus": "rgb(var(--interactive-outlined-primary-focus-base) / <alpha-value>)",
        "text-default-1": "rgb(var(--text-default-1-base) / <alpha-value>)",
        "text-default-2": "rgb(var(--text-default-2-base) / <alpha-value>)",
        "text-inverted-1": "rgb(var(--text-inverted-1-base) / <alpha-value>)",
        "text-inverted-2": "rgb(var(--text-inverted-2-base) / <alpha-value>)",
        "text-default-3": "rgb(var(--text-default-3-base) / <alpha-value>)",
        "text-inverted-3": "rgb(var(--text-inverted-3-base) / <alpha-value>)",
        "interactive-contained-primary-pressed":
          "rgb(var(--interactive-contained-primary-pressed-base) / <alpha-value>)",
        "interactive-contained-secondary-pressed":
          "rgb(var(--interactive-contained-secondary-pressed-base) / <alpha-value>)",
        "interactive-outlined-primary-outline-pressed":
          "rgb(var(--interactive-outlined-primary-outline-pressed-base) / <alpha-value>)",
        "elevation-fill-default-3": "rgb(var(--elevation-fill-default-3-base) / <alpha-value>)",
        "input-outlined-idle": "rgb(var(--input-outlined-idle-base) / <alpha-value>)",
        "input-outlined-active": "rgb(var(--input-outlined-active-base) / <alpha-value>)",
        "input-filled-idle": "rgb(var(--input-filled-idle-base) / <alpha-value>)",
        "input-filled-active": "rgb(var(--input-filled-active-base) / <alpha-value>)",
        "input-outlined-hover": "rgb(var(--input-outlined-hover-base) / <alpha-value>)",
        "input-outlined-error": "rgb(var(--input-outlined-error-base) / <alpha-value>)",
        "input-outlined-disabled": "rgb(var(--input-outlined-disabled-base) / <alpha-value>)",
        "input-filled-hover": "rgb(var(--input-filled-hover-base) / <alpha-value>)",
        "input-filled-error": "rgb(var(--input-filled-error-base) / <alpha-value>)",
        "input-filled-disabled": "rgb(var(--input-filled-disabled-base) / <alpha-value>)",
        "interactive-contained-success-on-idle":
          "rgb(var(--interactive-contained-success-on-idle-base) / <alpha-value>)",
        "interactive-contained-success-idle": "rgb(var(--interactive-contained-success-idle-base) / <alpha-value>)",
        "interactive-contained-success-hover": "rgb(var(--interactive-contained-success-hover-base) / <alpha-value>)",
        "interactive-contained-success-pressed":
          "rgb(var(--interactive-contained-success-pressed-base) / <alpha-value>)",
        "interactive-contained-success-disabled":
          "rgb(var(--interactive-contained-success-disabled-base) / <alpha-value>)",
        "interactive-contained-success-focus": "rgb(var(--interactive-contained-success-focus-base) / <alpha-value>)",
        "interactive-contained-warning-on-idle":
          "rgb(var(--interactive-contained-warning-on-idle-base) / <alpha-value>)",
        "interactive-contained-warning-idle": "rgb(var(--interactive-contained-warning-idle-base) / <alpha-value>)",
        "interactive-contained-warning-hover": "rgb(var(--interactive-contained-warning-hover-base) / <alpha-value>)",
        "interactive-contained-warning-pressed":
          "rgb(var(--interactive-contained-warning-pressed-base) / <alpha-value>)",
        "interactive-contained-warning-disabled":
          "rgb(var(--interactive-contained-warning-disabled-base) / <alpha-value>)",
        "interactive-contained-warning-focus": "rgb(var(--interactive-contained-warning-focus-base) / <alpha-value>)",
        "interactive-contained-error-on-idle": "rgb(var(--interactive-contained-error-on-idle-base) / <alpha-value>)",
        "interactive-contained-error-idle": "rgb(var(--interactive-contained-error-idle-base) / <alpha-value>)",
        "interactive-contained-error-hover": "rgb(var(--interactive-contained-error-hover-base) / <alpha-value>)",
        "interactive-contained-error-pressed": "rgb(var(--interactive-contained-error-pressed-base) / <alpha-value>)",
        "interactive-contained-error-disabled": "rgb(var(--interactive-contained-error-disabled-base) / <alpha-value>)",
        "interactive-contained-error-focus": "rgb(var(--interactive-contained-error-focus-base) / <alpha-value>)",
        "interactive-outlined-secondary-on-idle":
          "rgb(var(--interactive-outlined-secondary-on-idle-base) / <alpha-value>)",
        "interactive-outlined-secondary-outline-idle":
          "rgb(var(--interactive-outlined-secondary-outline-idle-base) / <alpha-value>)",
        "interactive-outlined-secondary-outline-hover":
          "rgb(var(--interactive-outlined-secondary-outline-hover-base) / <alpha-value>)",
        "interactive-outlined-secondary-outline-pressed":
          "rgb(var(--interactive-outlined-secondary-outline-pressed-base) / <alpha-value>)",
        "interactive-outlined-secondary-outline-disabled":
          "rgb(var(--interactive-outlined-secondary-outline-disabled-base) / <alpha-value>)",
        "interactive-outlined-secondary-focus": "rgb(var(--interactive-outlined-secondary-focus-base) / <alpha-value>)",
        "interactive-outlined-success-on-idle": "rgb(var(--interactive-outlined-success-on-idle-base) / <alpha-value>)",
        "interactive-outlined-success-outline-idle":
          "rgb(var(--interactive-outlined-success-outline-idle-base) / <alpha-value>)",
        "interactive-outlined-success-outline-hover":
          "rgb(var(--interactive-outlined-success-outline-hover-base) / <alpha-value>)",
        "interactive-outlined-success-outline-pressed":
          "rgb(var(--interactive-outlined-success-outline-pressed-base) / <alpha-value>)",
        "interactive-outlined-success-outline-disabled":
          "rgb(var(--interactive-outlined-success-outline-disabled-base) / <alpha-value>)",
        "interactive-outlined-success-focus": "rgb(var(--interactive-outlined-success-focus-base) / <alpha-value>)",
        "interactive-outlined-warning-on-idle": "rgb(var(--interactive-outlined-warning-on-idle-base) / <alpha-value>)",
        "interactive-outlined-warning-outline-idle":
          "rgb(var(--interactive-outlined-warning-outline-idle-base) / <alpha-value>)",
        "interactive-outlined-warning-outline-hover":
          "rgb(var(--interactive-outlined-warning-outline-hover-base) / <alpha-value>)",
        "interactive-outlined-warning-outline-pressed":
          "rgb(var(--interactive-outlined-warning-outline-pressed-base) / <alpha-value>)",
        "interactive-outlined-warning-outline-disabled":
          "rgb(var(--interactive-outlined-warning-outline-disabled-base) / <alpha-value>)",
        "interactive-outlined-warning-focus": "rgb(var(--interactive-outlined-warning-focus-base) / <alpha-value>)",
        "interactive-outlined-error-on-idle": "rgb(var(--interactive-outlined-error-on-idle-base) / <alpha-value>)",
        "interactive-outlined-error-outline-idle":
          "rgb(var(--interactive-outlined-error-outline-idle-base) / <alpha-value>)",
        "interactive-outlined-error-outline-hover":
          "rgb(var(--interactive-outlined-error-outline-hover-base) / <alpha-value>)",
        "interactive-outlined-error-outline-pressed":
          "rgb(var(--interactive-outlined-error-outline-pressed-base) / <alpha-value>)",
        "interactive-outlined-error-outline-disabled":
          "rgb(var(--interactive-outlined-error-outline-disabled-base) / <alpha-value>)",
        "interactive-outlined-error-focus": "rgb(var(--interactive-outlined-error-focus-base) / <alpha-value>)",
        "interactive-subtle-primary-on-idle": "rgb(var(--interactive-subtle-primary-on-idle-base) / <alpha-value>)",
        "interactive-subtle-primary-idle": "rgb(var(--interactive-subtle-primary-idle-base) / <alpha-value>)",
        "interactive-subtle-primary-hover": "rgb(var(--interactive-subtle-primary-hover-base) / <alpha-value>)",
        "interactive-subtle-primary-pressed": "rgb(var(--interactive-subtle-primary-pressed-base) / <alpha-value>)",
        "interactive-subtle-primary-disabled": "rgb(var(--interactive-subtle-primary-disabled-base) / <alpha-value>)",
        "interactive-subtle-primary-focus": "rgb(var(--interactive-subtle-primary-focus-base) / <alpha-value>)",
        "interactive-subtle-secondary-on-idle": "rgb(var(--interactive-subtle-secondary-on-idle-base) / <alpha-value>)",
        "interactive-subtle-secondary-idle": "rgb(var(--interactive-subtle-secondary-idle-base) / <alpha-value>)",
        "interactive-subtle-secondary-hover": "rgb(var(--interactive-subtle-secondary-hover-base) / <alpha-value>)",
        "interactive-subtle-secondary-pressed": "rgb(var(--interactive-subtle-secondary-pressed-base) / <alpha-value>)",
        "interactive-subtle-secondary-disabled":
          "rgb(var(--interactive-subtle-secondary-disabled-base) / <alpha-value>)",
        "interactive-subtle-secondary-focus": "rgb(var(--interactive-subtle-secondary-focus-base) / <alpha-value>)",
        "interactive-subtle-success-on-idle": "rgb(var(--interactive-subtle-success-on-idle-base) / <alpha-value>)",
        "interactive-subtle-success-idle": "rgb(var(--interactive-subtle-success-idle-base) / <alpha-value>)",
        "interactive-subtle-success-hover": "rgb(var(--interactive-subtle-success-hover-base) / <alpha-value>)",
        "interactive-subtle-success-pressed": "rgb(var(--interactive-subtle-success-pressed-base) / <alpha-value>)",
        "interactive-subtle-success-disabled": "rgb(var(--interactive-subtle-success-disabled-base) / <alpha-value>)",
        "interactive-subtle-success-focus": "rgb(var(--interactive-subtle-success-focus-base) / <alpha-value>)",
        "interactive-subtle-warning-on-idle": "rgb(var(--interactive-subtle-warning-on-idle-base) / <alpha-value>)",
        "interactive-subtle-warning-idle": "rgb(var(--interactive-subtle-warning-idle-base) / <alpha-value>)",
        "interactive-subtle-warning-hover": "rgb(var(--interactive-subtle-warning-hover-base) / <alpha-value>)",
        "interactive-subtle-warning-pressed": "rgb(var(--interactive-subtle-warning-pressed-base) / <alpha-value>)",
        "interactive-subtle-warning-disabled": "rgb(var(--interactive-subtle-warning-disabled-base) / <alpha-value>)",
        "interactive-subtle-warning-focus": "rgb(var(--interactive-subtle-warning-focus-base) / <alpha-value>)",
        "interactive-subtle-error-on-idle": "rgb(var(--interactive-subtle-error-on-idle-base) / <alpha-value>)",
        "interactive-subtle-error-idle": "rgb(var(--interactive-subtle-error-idle-base) / <alpha-value>)",
        "interactive-subtle-error-hover": "rgb(var(--interactive-subtle-error-hover-base) / <alpha-value>)",
        "interactive-subtle-error-pressed": "rgb(var(--interactive-subtle-error-pressed-base) / <alpha-value>)",
        "interactive-subtle-error-disabled": "rgb(var(--interactive-subtle-error-disabled-base) / <alpha-value>)",
        "interactive-subtle-error-focus": "rgb(var(--interactive-subtle-error-focus-base) / <alpha-value>)",
        "interactive-subtle-primary-on-disabled":
          "rgb(var(--interactive-subtle-primary-on-disabled-base) / <alpha-value>)",
        "interactive-subtle-secondary-on-disabled":
          "rgb(var(--interactive-subtle-secondary-on-disabled-base) / <alpha-value>)",
        "interactive-subtle-success-on-disabled":
          "rgb(var(--interactive-subtle-success-on-disabled-base) / <alpha-value>)",
        "interactive-subtle-warning-on-disabled":
          "rgb(var(--interactive-subtle-warning-on-disabled-base) / <alpha-value>)",
        "interactive-subtle-error-on-disabled": "rgb(var(--interactive-subtle-error-on-disabled-base) / <alpha-value>)",
        "text-success-1": "rgb(var(--text-success-1-base) / <alpha-value>)",
        "text-warning-1": "rgb(var(--text-warning-1-base) / <alpha-value>)",
        "text-error-1": "rgb(var(--text-error-1-base) / <alpha-value>)",
        "interactive-text-primary-idle": "rgb(var(--interactive-text-primary-idle-base) / <alpha-value>)",
        "interactive-text-primary-hover": "rgb(var(--interactive-text-primary-hover-base) / <alpha-value>)",
        "interactive-text-primary-pressed": "rgb(var(--interactive-text-primary-pressed-base) / <alpha-value>)",
        "interactive-text-primary-disabled": "rgb(var(--interactive-text-primary-disabled-base) / <alpha-value>)",
        "interactive-text-primary-idle-inverted":
          "rgb(var(--interactive-text-primary-idle-inverted-base) / <alpha-value>)",
        "interactive-text-primary-hover-inverted":
          "rgb(var(--interactive-text-primary-hover-inverted-base) / <alpha-value>)",
        "interactive-text-primary-pressed-inverted":
          "rgb(var(--interactive-text-primary-pressed-inverted-base) / <alpha-value>)",
        "interactive-text-secondary-idle": "rgb(var(--interactive-text-secondary-idle-base) / <alpha-value>)",
        "interactive-text-secondary-hover": "rgb(var(--interactive-text-secondary-hover-base) / <alpha-value>)",
        "interactive-text-secondary-pressed": "rgb(var(--interactive-text-secondary-pressed-base) / <alpha-value>)",
        "interactive-text-secondary-disabled": "rgb(var(--interactive-text-secondary-disabled-base) / <alpha-value>)",
        "interactive-text-secondary-idle-inverted":
          "rgb(var(--interactive-text-secondary-idle-inverted-base) / <alpha-value>)",
        "interactive-text-secondary-hover-inverted":
          "rgb(var(--interactive-text-secondary-hover-inverted-base) / <alpha-value>)",
        "interactive-text-secondary-pressed-inverted":
          "rgb(var(--interactive-text-secondary-pressed-inverted-base) / <alpha-value>)",
        "interactive-text-success-idle": "rgb(var(--interactive-text-success-idle-base) / <alpha-value>)",
        "interactive-text-success-hover": "rgb(var(--interactive-text-success-hover-base) / <alpha-value>)",
        "interactive-text-success-pressed": "rgb(var(--interactive-text-success-pressed-base) / <alpha-value>)",
        "interactive-text-success-disabled": "rgb(var(--interactive-text-success-disabled-base) / <alpha-value>)",
        "interactive-text-success-idle-inverted":
          "rgb(var(--interactive-text-success-idle-inverted-base) / <alpha-value>)",
        "interactive-text-success-hover-inverted":
          "rgb(var(--interactive-text-success-hover-inverted-base) / <alpha-value>)",
        "interactive-text-success-pressed-inverted":
          "rgb(var(--interactive-text-success-pressed-inverted-base) / <alpha-value>)",
        "interactive-text-warning-idle": "rgb(var(--interactive-text-warning-idle-base) / <alpha-value>)",
        "interactive-text-warning-hover": "rgb(var(--interactive-text-warning-hover-base) / <alpha-value>)",
        "interactive-text-warning-pressed": "rgb(var(--interactive-text-warning-pressed-base) / <alpha-value>)",
        "interactive-text-warning-disabled": "rgb(var(--interactive-text-warning-disabled-base) / <alpha-value>)",
        "interactive-text-warning-idle-inverted":
          "rgb(var(--interactive-text-warning-idle-inverted-base) / <alpha-value>)",
        "interactive-text-warning-hover-inverted":
          "rgb(var(--interactive-text-warning-hover-inverted-base) / <alpha-value>)",
        "interactive-text-warning-pressed-inverted":
          "rgb(var(--interactive-text-warning-pressed-inverted-base) / <alpha-value>)",
        "interactive-text-error-idle": "rgb(var(--interactive-text-error-idle-base) / <alpha-value>)",
        "interactive-text-error-hover": "rgb(var(--interactive-text-error-hover-base) / <alpha-value>)",
        "interactive-text-error-pressed": "rgb(var(--interactive-text-error-pressed-base) / <alpha-value>)",
        "interactive-text-error-disabled": "rgb(var(--interactive-text-error-disabled-base) / <alpha-value>)",
        "interactive-text-error-idle-inverted": "rgb(var(--interactive-text-error-idle-inverted-base) / <alpha-value>)",
        "interactive-text-error-hover-inverted":
          "rgb(var(--interactive-text-error-hover-inverted-base) / <alpha-value>)",
        "interactive-text-error-pressed-inverted":
          "rgb(var(--interactive-text-error-pressed-inverted-base) / <alpha-value>)",
        "interactive-outlined-primary-hover": "rgb(var(--interactive-outlined-primary-hover-base) / <alpha-value>)",
        "interactive-outlined-secondary-hover": "rgb(var(--interactive-outlined-secondary-hover-base) / <alpha-value>)",
        "interactive-outlined-success-hover": "rgb(var(--interactive-outlined-success-hover-base) / <alpha-value>)",
        "interactive-outlined-warning-hover": "rgb(var(--interactive-outlined-warning-hover-base) / <alpha-value>)",
        "interactive-outlined-error-hover": "rgb(var(--interactive-outlined-error-hover-base) / <alpha-value>)",
        "elevation-outline-default-3": "rgb(var(--elevation-outline-default-3-base) / <alpha-value>)",
        "elevation-outline-inverted-1": "rgb(var(--elevation-outline-inverted-1-base) / <alpha-value>)",
        "elevation-outline-inverted-2": "rgb(var(--elevation-outline-inverted-2-base) / <alpha-value>)",
        "elevation-outline-inverted-3": "rgb(var(--elevation-outline-inverted-3-base) / <alpha-value>)",
        "elevation-outline-success-1": "rgb(var(--elevation-outline-success-1-base) / <alpha-value>)",
        "elevation-outline-warning-1": "rgb(var(--elevation-outline-warning-1-base) / <alpha-value>)",
        "elevation-outline-error-1": "rgb(var(--elevation-outline-error-1-base) / <alpha-value>)",
        "elevation-fill-inverted-1": "rgb(var(--elevation-fill-inverted-1-base) / <alpha-value>)",
        "elevation-fill-inverted-2": "rgb(var(--elevation-fill-inverted-2-base) / <alpha-value>)",
        "elevation-fill-inverted-3": "rgb(var(--elevation-fill-inverted-3-base) / <alpha-value>)",
        "elevation-fill-success-1": "rgb(var(--elevation-fill-success-1-base) / <alpha-value>)",
        "elevation-fill-warning-1": "rgb(var(--elevation-fill-warning-1-base) / <alpha-value>)",
        "elevation-fill-error-1": "rgb(var(--elevation-fill-error-1-base) / <alpha-value>)",
        "text-success-2": "rgb(var(--text-success-2-base) / <alpha-value>)",
        "text-warning-2": "rgb(var(--text-warning-2-base) / <alpha-value>)",
        "text-error-2": "rgb(var(--text-error-2-base) / <alpha-value>)",
        "text-success-3": "rgb(var(--text-success-3-base) / <alpha-value>)",
        "text-warning-3": "rgb(var(--text-warning-3-base) / <alpha-value>)",
        "text-error-3": "rgb(var(--text-error-3-base) / <alpha-value>)",
        "interactive-contained-primary-on-hover":
          "rgb(var(--interactive-contained-primary-on-hover-base) / <alpha-value>)",
        "interactive-contained-primary-on-pressed":
          "rgb(var(--interactive-contained-primary-on-pressed-base) / <alpha-value>)",
        "interactive-contained-primary-on-disabled":
          "rgb(var(--interactive-contained-primary-on-disabled-base) / <alpha-value>)",
        "interactive-contained-secondary-on-hover":
          "rgb(var(--interactive-contained-secondary-on-hover-base) / <alpha-value>)",
        "interactive-contained-secondary-on-pressed":
          "rgb(var(--interactive-contained-secondary-on-pressed-base) / <alpha-value>)",
        "interactive-contained-secondary-on-disabled":
          "rgb(var(--interactive-contained-secondary-on-disabled-base) / <alpha-value>)",
        "interactive-contained-success-on-hover":
          "rgb(var(--interactive-contained-success-on-hover-base) / <alpha-value>)",
        "interactive-contained-success-on-pressed":
          "rgb(var(--interactive-contained-success-on-pressed-base) / <alpha-value>)",
        "interactive-contained-success-on-disabled":
          "rgb(var(--interactive-contained-success-on-disabled-base) / <alpha-value>)",
        "interactive-contained-warning-on-hover":
          "rgb(var(--interactive-contained-warning-on-hover-base) / <alpha-value>)",
        "interactive-contained-warning-on-pressed":
          "rgb(var(--interactive-contained-warning-on-pressed-base) / <alpha-value>)",
        "interactive-contained-warning-on-disabled":
          "rgb(var(--interactive-contained-warning-on-disabled-base) / <alpha-value>)",
        "interactive-contained-error-on-hover": "rgb(var(--interactive-contained-error-on-hover-base) / <alpha-value>)",
        "interactive-contained-error-on-pressed":
          "rgb(var(--interactive-contained-error-on-pressed-base) / <alpha-value>)",
        "interactive-contained-error-on-disabled":
          "rgb(var(--interactive-contained-error-on-disabled-base) / <alpha-value>)",
        "interactive-outlined-primary-on-hover":
          "rgb(var(--interactive-outlined-primary-on-hover-base) / <alpha-value>)",
        "interactive-outlined-primary-on-pressed":
          "rgb(var(--interactive-outlined-primary-on-pressed-base) / <alpha-value>)",
        "interactive-outlined-primary-on-disabled":
          "rgb(var(--interactive-outlined-primary-on-disabled-base) / <alpha-value>)",
        "interactive-outlined-secondary-on-hover":
          "rgb(var(--interactive-outlined-secondary-on-hover-base) / <alpha-value>)",
        "interactive-outlined-secondary-on-pressed":
          "rgb(var(--interactive-outlined-secondary-on-pressed-base) / <alpha-value>)",
        "interactive-outlined-secondary-on-disabled":
          "rgb(var(--interactive-outlined-secondary-on-disabled-base) / <alpha-value>)",
        "interactive-outlined-success-on-hover":
          "rgb(var(--interactive-outlined-success-on-hover-base) / <alpha-value>)",
        "interactive-outlined-success-on-pressed":
          "rgb(var(--interactive-outlined-success-on-pressed-base) / <alpha-value>)",
        "interactive-outlined-success-on-disabled":
          "rgb(var(--interactive-outlined-success-on-disabled-base) / <alpha-value>)",
        "interactive-outlined-warning-on-hover":
          "rgb(var(--interactive-outlined-warning-on-hover-base) / <alpha-value>)",
        "interactive-outlined-warning-on-pressed":
          "rgb(var(--interactive-outlined-warning-on-pressed-base) / <alpha-value>)",
        "interactive-outlined-warning-on-disabled":
          "rgb(var(--interactive-outlined-warning-on-disabled-base) / <alpha-value>)",
        "interactive-outlined-error-on-hover": "rgb(var(--interactive-outlined-error-on-hover-base) / <alpha-value>)",
        "interactive-outlined-error-on-pressed":
          "rgb(var(--interactive-outlined-error-on-pressed-base) / <alpha-value>)",
        "interactive-outlined-error-on-disabled":
          "rgb(var(--interactive-outlined-error-on-disabled-base) / <alpha-value>)",
        "interactive-subtle-primary-toggled-idle":
          "rgb(var(--interactive-subtle-primary-toggled-idle-base) / <alpha-value>)",
        "interactive-subtle-primary-on-hover": "rgb(var(--interactive-subtle-primary-on-hover-base) / <alpha-value>)",
        "interactive-subtle-primary-on-pressed":
          "rgb(var(--interactive-subtle-primary-on-pressed-base) / <alpha-value>)",
        "interactive-subtle-primary-on-toggled-idle":
          "rgb(var(--interactive-subtle-primary-on-toggled-idle-base) / <alpha-value>)",
        "interactive-subtle-secondary-toggled-idle":
          "rgb(var(--interactive-subtle-secondary-toggled-idle-base) / <alpha-value>)",
        "interactive-subtle-secondary-on-hover":
          "rgb(var(--interactive-subtle-secondary-on-hover-base) / <alpha-value>)",
        "interactive-subtle-secondary-on-pressed":
          "rgb(var(--interactive-subtle-secondary-on-pressed-base) / <alpha-value>)",
        "interactive-subtle-secondary-on-toggled-idle":
          "rgb(var(--interactive-subtle-secondary-on-toggled-idle-base) / <alpha-value>)",
        "interactive-subtle-success-on-hover": "rgb(var(--interactive-subtle-success-on-hover-base) / <alpha-value>)",
        "interactive-subtle-success-on-pressed":
          "rgb(var(--interactive-subtle-success-on-pressed-base) / <alpha-value>)",
        "interactive-subtle-warning-on-hover": "rgb(var(--interactive-subtle-warning-on-hover-base) / <alpha-value>)",
        "interactive-subtle-warning-on-pressed":
          "rgb(var(--interactive-subtle-warning-on-pressed-base) / <alpha-value>)",
        "interactive-subtle-error-on-hover": "rgb(var(--interactive-subtle-error-on-hover-base) / <alpha-value>)",
        "interactive-subtle-error-on-pressed": "rgb(var(--interactive-subtle-error-on-pressed-base) / <alpha-value>)",
        "interactive-outlined-primary-on-toggled-idle":
          "rgb(var(--interactive-outlined-primary-on-toggled-idle-base) / <alpha-value>)",
        "interactive-outlined-primary-on-toggled-hover":
          "rgb(var(--interactive-outlined-primary-on-toggled-hover-base) / <alpha-value>)",
        "interactive-outlined-primary-on-toggled-disabled":
          "rgb(var(--interactive-outlined-primary-on-toggled-disabled-base) / <alpha-value>)",
        "interactive-outlined-primary-toggled-idle":
          "rgb(var(--interactive-outlined-primary-toggled-idle-base) / <alpha-value>)",
        "interactive-outlined-primary-toggled-hover":
          "rgb(var(--interactive-outlined-primary-toggled-hover-base) / <alpha-value>)",
        "interactive-outlined-primary-toggled-disabled":
          "rgb(var(--interactive-outlined-primary-toggled-disabled-base) / <alpha-value>)",
        "interactive-outlined-primary-pressed": "rgb(var(--interactive-outlined-primary-pressed-base) / <alpha-value>)",
        "interactive-outlined-secondary-pressed":
          "rgb(var(--interactive-outlined-secondary-pressed-base) / <alpha-value>)",
        "interactive-outlined-secondary-on-toggled-idle":
          "rgb(var(--interactive-outlined-secondary-on-toggled-idle-base) / <alpha-value>)",
        "interactive-outlined-secondary-on-toggled-hover":
          "rgb(var(--interactive-outlined-secondary-on-toggled-hover-base) / <alpha-value>)",
        "interactive-outlined-secondary-on-toggled-disabled":
          "rgb(var(--interactive-outlined-secondary-on-toggled-disabled-base) / <alpha-value>)",
        "interactive-outlined-secondary-toggled-idle":
          "rgb(var(--interactive-outlined-secondary-toggled-idle-base) / <alpha-value>)",
        "interactive-outlined-secondary-toggled-hover":
          "rgb(var(--interactive-outlined-secondary-toggled-hover-base) / <alpha-value>)",
        "interactive-outlined-secondary-toggled-disabled":
          "rgb(var(--interactive-outlined-secondary-toggled-disabled-base) / <alpha-value>)",
        "interactive-outlined-success-pressed": "rgb(var(--interactive-outlined-success-pressed-base) / <alpha-value>)",
        "interactive-outlined-warning-pressed": "rgb(var(--interactive-outlined-warning-pressed-base) / <alpha-value>)",
        "interactive-outlined-error-pressed": "rgb(var(--interactive-outlined-error-pressed-base) / <alpha-value>)",
        "elevation-fill-inverted-4": "rgb(var(--elevation-fill-inverted-4-base) / <alpha-value>)",
        "interactive-text-primary-focus": "rgb(var(--interactive-text-primary-focus-base) / <alpha-value>)",
        "interactive-text-secondary-focus": "rgb(var(--interactive-text-secondary-focus-base) / <alpha-value>)",
        "interactive-text-secondary-focus-inverted":
          "rgb(var(--interactive-text-secondary-focus-inverted-base) / <alpha-value>)",
        "interactive-text-primary-focus-inverted":
          "rgb(var(--interactive-text-primary-focus-inverted-base) / <alpha-value>)",
        "interactive-text-success-focus": "rgb(var(--interactive-text-success-focus-base) / <alpha-value>)",
        "interactive-text-success-focus-inverted":
          "rgb(var(--interactive-text-success-focus-inverted-base) / <alpha-value>)",
        "interactive-text-warning-focus": "rgb(var(--interactive-text-warning-focus-base) / <alpha-value>)",
        "interactive-text-warning-focus-inverted":
          "rgb(var(--interactive-text-warning-focus-inverted-base) / <alpha-value>)",
        "interactive-text-error-focus": "rgb(var(--interactive-text-error-focus-base) / <alpha-value>)",
        "interactive-text-error-focus-inverted":
          "rgb(var(--interactive-text-error-focus-inverted-base) / <alpha-value>)",
        "interactive-subtle-secondary-on-toggled-hover":
          "rgb(var(--interactive-subtle-secondary-on-toggled-hover-base) / <alpha-value>)",
        "interactive-subtle-secondary-on-toggled-disabled":
          "rgb(var(--interactive-subtle-secondary-on-toggled-disabled-base) / <alpha-value>)",
        "interactive-subtle-secondary-toggled-hover":
          "rgb(var(--interactive-subtle-secondary-toggled-hover-base) / <alpha-value>)",
        "interactive-subtle-secondary-toggled-disabled":
          "rgb(var(--interactive-subtle-secondary-toggled-disabled-base) / <alpha-value>)",
        "interactive-text-primary-disabled-inverted":
          "rgb(var(--interactive-text-primary-disabled-inverted-base) / <alpha-value>)",
        "interactive-text-secondary-disabled-inverted":
          "rgb(var(--interactive-text-secondary-disabled-inverted-base) / <alpha-value>)",
        "interactive-text-success-disabled-inverted":
          "rgb(var(--interactive-text-success-disabled-inverted-base) / <alpha-value>)",
        "interactive-text-warning-disabled-inverted":
          "rgb(var(--interactive-text-warning-disabled-inverted-base) / <alpha-value>)",
        "interactive-text-error-disabled-inverted":
          "rgb(var(--interactive-text-error-disabled-inverted-base) / <alpha-value>)",
        "interactive-subtle-primary-on-toggled-hover":
          "rgb(var(--interactive-subtle-primary-on-toggled-hover-base) / <alpha-value>)",
        "interactive-subtle-primary-on-toggled-disabled":
          "rgb(var(--interactive-subtle-primary-on-toggled-disabled-base) / <alpha-value>)",
        "interactive-subtle-primary-toggled-hover":
          "rgb(var(--interactive-subtle-primary-toggled-hover-base) / <alpha-value>)",
        "interactive-subtle-primary-toggled-disabled":
          "rgb(var(--interactive-subtle-primary-toggled-disabled-base) / <alpha-value>)",
        "input-outlined-outline-idle": "rgb(var(--input-outlined-outline-idle-base) / <alpha-value>)",
        "input-outlined-outline-hover": "rgb(var(--input-outlined-outline-hover-base) / <alpha-value>)",
        "input-outlined-outline-active": "rgb(var(--input-outlined-outline-active-base) / <alpha-value>)",
        "input-outlined-outline-error": "rgb(var(--input-outlined-outline-error-base) / <alpha-value>)",
        "input-outlined-outline-disabled": "rgb(var(--input-outlined-outline-disabled-base) / <alpha-value>)",
        "input-filled-outline-error": "rgb(var(--input-filled-outline-error-base) / <alpha-value>)",
        "input-filled-outline-hover": "rgb(var(--input-filled-outline-hover-base) / <alpha-value>)",
        "input-filled-outline-active": "rgb(var(--input-filled-outline-active-base) / <alpha-value>)",
        "interactive-contained-primary-on-toggled-disabled":
          "rgb(var(--interactive-contained-primary-on-toggled-disabled-base) / <alpha-value>)",
        "interactive-contained-primary-on-toggled-idle":
          "rgb(var(--interactive-contained-primary-on-toggled-idle-base) / <alpha-value>)",
        "interactive-contained-primary-toggled-disabled":
          "rgb(var(--interactive-contained-primary-toggled-disabled-base) / <alpha-value>)",
        "interactive-contained-primary-toggled-idle":
          "rgb(var(--interactive-contained-primary-toggled-idle-base) / <alpha-value>)",
        "interactive-contained-secondary-on-toggled-disabled":
          "rgb(var(--interactive-contained-secondary-on-toggled-disabled-base) / <alpha-value>)",
        "interactive-contained-secondary-on-toggled-idle":
          "rgb(var(--interactive-contained-secondary-on-toggled-idle-base) / <alpha-value>)",
        "interactive-contained-secondary-toggled-disabled":
          "rgb(var(--interactive-contained-secondary-toggled-disabled-base) / <alpha-value>)",
        "interactive-contained-secondary-toggled-idle":
          "rgb(var(--interactive-contained-secondary-toggled-idle-base) / <alpha-value>)",
        "interactive-contained-success-on-toggled-disabled":
          "rgb(var(--interactive-contained-success-on-toggled-disabled-base) / <alpha-value>)",
        "interactive-contained-success-on-toggled-idle":
          "rgb(var(--interactive-contained-success-on-toggled-idle-base) / <alpha-value>)",
        "interactive-contained-success-toggled-disabled":
          "rgb(var(--interactive-contained-success-toggled-disabled-base) / <alpha-value>)",
        "interactive-contained-success-toggled-idle":
          "rgb(var(--interactive-contained-success-toggled-idle-base) / <alpha-value>)",
        "interactive-contained-warning-on-toggled-idle":
          "rgb(var(--interactive-contained-warning-on-toggled-idle-base) / <alpha-value>)",
        "interactive-contained-warning-toggled-disabled":
          "rgb(var(--interactive-contained-warning-toggled-disabled-base) / <alpha-value>)",
        "interactive-contained-warning-on-toggled-disabled":
          "rgb(var(--interactive-contained-warning-on-toggled-disabled-base) / <alpha-value>)",
        "interactive-contained-warning-toggled-idle":
          "rgb(var(--interactive-contained-warning-toggled-idle-base) / <alpha-value>)",
        "interactive-contained-error-toggled-disabled":
          "rgb(var(--interactive-contained-error-toggled-disabled-base) / <alpha-value>)",
        "interactive-contained-error-on-toggled-disabled":
          "rgb(var(--interactive-contained-error-on-toggled-disabled-base) / <alpha-value>)",
        "interactive-contained-error-on-toggled-idle":
          "rgb(var(--interactive-contained-error-on-toggled-idle-base) / <alpha-value>)",
        "interactive-contained-error-toggled-idle":
          "rgb(var(--interactive-contained-error-toggled-idle-base) / <alpha-value>)",
        "interactive-subtle-success-toggled-disabled":
          "rgb(var(--interactive-subtle-success-toggled-disabled-base) / <alpha-value>)",
        "interactive-subtle-success-on-toggled-disabled":
          "rgb(var(--interactive-subtle-success-on-toggled-disabled-base) / <alpha-value>)",
        "interactive-subtle-success-on-toggled-idle":
          "rgb(var(--interactive-subtle-success-on-toggled-idle-base) / <alpha-value>)",
        "interactive-subtle-success-toggled-idle":
          "rgb(var(--interactive-subtle-success-toggled-idle-base) / <alpha-value>)",
        "interactive-subtle-warning-on-toggled-idle":
          "rgb(var(--interactive-subtle-warning-on-toggled-idle-base) / <alpha-value>)",
        "interactive-subtle-warning-toggled-disabled":
          "rgb(var(--interactive-subtle-warning-toggled-disabled-base) / <alpha-value>)",
        "interactive-subtle-warning-toggled-idle":
          "rgb(var(--interactive-subtle-warning-toggled-idle-base) / <alpha-value>)",
        "interactive-subtle-warning-on-toggled-disabled":
          "rgb(var(--interactive-subtle-warning-on-toggled-disabled-base) / <alpha-value>)",
        "interactive-subtle-error-toggled-idle":
          "rgb(var(--interactive-subtle-error-toggled-idle-base) / <alpha-value>)",
        "interactive-subtle-error-on-toggled-disabled":
          "rgb(var(--interactive-subtle-error-on-toggled-disabled-base) / <alpha-value>)",
        "interactive-subtle-error-toggled-disabled":
          "rgb(var(--interactive-subtle-error-toggled-disabled-base) / <alpha-value>)",
        "interactive-subtle-error-on-toggled-idle":
          "rgb(var(--interactive-subtle-error-on-toggled-idle-base) / <alpha-value>)",
        "interactive-contained-primary-toggled-hovered":
          "rgb(var(--interactive-contained-primary-toggled-hovered-base) / <alpha-value>)",
        "interactive-contained-primary-on-toggled-hovered":
          "rgb(var(--interactive-contained-primary-on-toggled-hovered-base) / <alpha-value>)",
        "interactive-contained-secondary-toggled-hovered":
          "rgb(var(--interactive-contained-secondary-toggled-hovered-base) / <alpha-value>)",
        "interactive-contained-secondary-on-toggled-hovered":
          "rgb(var(--interactive-contained-secondary-on-toggled-hovered-base) / <alpha-value>)",
        "interactive-contained-success-toggled-hovered":
          "rgb(var(--interactive-contained-success-toggled-hovered-base) / <alpha-value>)",
        "interactive-contained-success-on-toggled-hovered":
          "rgb(var(--interactive-contained-success-on-toggled-hovered-base) / <alpha-value>)",
        "interactive-subtle-success-toggled-hovered":
          "rgb(var(--interactive-subtle-success-toggled-hovered-base) / <alpha-value>)",
        "interactive-subtle-success-on-toggled-hovered":
          "rgb(var(--interactive-subtle-success-on-toggled-hovered-base) / <alpha-value>)",
        "interactive-contained-warning-toggled-hovered":
          "rgb(var(--interactive-contained-warning-toggled-hovered-base) / <alpha-value>)",
        "interactive-contained-warning-on-toggled-hovered":
          "rgb(var(--interactive-contained-warning-on-toggled-hovered-base) / <alpha-value>)",
        "interactive-subtle-warning-toggled-hovered":
          "rgb(var(--interactive-subtle-warning-toggled-hovered-base) / <alpha-value>)",
        "interactive-subtle-warning-on-toggled-hovered":
          "rgb(var(--interactive-subtle-warning-on-toggled-hovered-base) / <alpha-value>)",
        "interactive-contained-error-toggled-hovered":
          "rgb(var(--interactive-contained-error-toggled-hovered-base) / <alpha-value>)",
        "interactive-contained-error-on-toggled-hovered":
          "rgb(var(--interactive-contained-error-on-toggled-hovered-base) / <alpha-value>)",
        "interactive-subtle-error-on-toggled-hovered":
          "rgb(var(--interactive-subtle-error-on-toggled-hovered-base) / <alpha-value>)",
        "interactive-subtle-error-toggled-hovered":
          "rgb(var(--interactive-subtle-error-toggled-hovered-base) / <alpha-value>)",
      },
      borderRadius: {
        none: "0rem",
        "2xs": "0.125rem",
        xs: "0.25rem",
        s: "0.375rem",
        sm: "0.5rem",
        ml: "0.75rem",
        xl: "1rem",
        "4xl": "1.5rem",
        full: "624.9375rem",
        "5xl": "1.75rem",
        "6xl": "2rem",
        m: "0.625rem",
        l: "0.875rem",
        "2xl": "1.125rem",
        "3xl": "1.25rem",
        "global-rounding-xs": "0.25rem",
        "global-rounding-s": "0.375rem",
        "global-rounding-m": "0.5rem",
        "global-rounding-l": "0.625rem",
        "global-rounding-xl": "0.75rem",
        "input-rounding-default": "0.375rem",
        "list-rounding-actions": "0rem",
        "list-rounding-drawer": "1rem",
        "modal-rounding-default": "0.75rem",
        "toast-rounding-default": "0.5rem",
        "tooltip-rounding-default": "0.5rem",
        "button-rounding-m": "0.375rem",
        "alert-rounding-default": "0.5rem",
        "pill-rounding-default": "0.375rem",
        "button-focus-rounding-m": "0.5rem",
        "list-rounding-dropdown": "0.375rem",
        "button-rounding-s": "0.25rem",
        "button-rounding-xs": "0.125rem",
        "button-rounding-l": "0.5rem",
        "button-rounding-xl": "0.625rem",
        "button-focus-rounding-s": "0.375rem",
        "button-focus-rounding-l": "0.625rem",
        "button-focus-rounding-xl": "0.75rem",
        "file-upload-container-rounding-default": "0.375rem",
        "file-upload-file-card-rounding-default": "0.375rem",
        "image-upload-container-clipping-layer-default": "0rem",
        "segmented-control-rounding-segment": "0.375rem",
        "image-upload-avatar-with-buttons-rounding-default": "624.9375rem",
        "image-overlay-inside-rounding-full": "624.9375rem",
        "segmented-control-rounding-segmented-control": "0.5rem",
        "image-overlay-outside-rounding-full": "624.9375rem",
        "avatar-rounding-default": "624.9375rem",
        "progress-rounding-default": "0.25rem",
        "slider-rounding-default": "0.25rem",
      },
      maxWidth: {
        "0": "0rem",
        "1": "0.25rem",
        "2": "0.5rem",
        "3": "0.75rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "7": "1.75rem",
        "8": "2rem",
        "9": "2.25rem",
        "10": "2.5rem",
        "11": "2.75rem",
        "12": "3rem",
        "14": "3.5rem",
        "16": "4rem",
        "18": "4.5rem",
        "20": "5rem",
        "24": "6rem",
        "28": "7rem",
        "32": "8rem",
        "36": "9rem",
        "40": "10rem",
        "44": "11rem",
        "48": "12rem",
        "52": "13rem",
        "56": "14rem",
        "60": "15rem",
        "64": "16rem",
        "72": "18rem",
        "80": "20rem",
        "96": "24rem",
        xs: "20rem",
        sm: "24rem",
        md: "28rem",
        lg: "32rem",
        xl: "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "7xl": "80rem",
        "2xs": "16rem",
        "3xs": "12rem",
        "3-5xs": "9.75rem",
        "4xs": "8rem",
        "4-5xs": "7rem",
        "5-5xs": "4.75rem",
        "5xs": "6rem",
        px: "0.0625rem",
        "0-5": "0.125rem",
        "1-5": "0.375rem",
        "2-5": "0.625rem",
        "3-5": "0.875rem",
        "avatar-height-xs": "1.5rem",
        "avatar-height-s": "2rem",
        "avatar-height-m": "2.5rem",
        "avatar-height-l": "3.5rem",
        "avatar-height-xl": "4.5rem",
        "avatar-height-xxl": "6rem",
        "button-width-min-width-xxs": "1.625rem",
        "button-width-min-width-xs": "1.875rem",
        "button-width-min-width-s": "2.125rem",
        "button-width-min-width-m": "2.875rem",
        "button-width-min-width-l": "3.625rem",
        "global-side-xs": "0.125rem",
        "global-side-s": "0.25rem",
        "global-side-m": "0.625rem",
        "global-side-l": "1rem",
        "global-side-xl": "1.25rem",
        "global-gap-xs": "0.25rem",
        "global-gap-s": "0.5rem",
        "global-gap-m": "0.75rem",
        "global-gap-l": "1rem",
        "global-gap-xl": "1.25rem",
        "global-gap-ml": "0.875rem",
        "global-gap-sm": "0.625rem",
        "global-side-sm": "0.375rem",
        "global-side-ml": "0.75rem",
        "global-height-xs": "0.125rem",
        "global-height-s": "0.25rem",
        "global-height-m": "0.625rem",
        "global-height-l": "0.875rem",
        "global-height-xl": "1rem",
        "button-height-s": "0.25rem",
        "button-height-m": "0.625rem",
        "button-height-l": "1rem",
        "button-side-s": "0.25rem",
        "button-side-m": "1rem",
        "button-side-l": "1.75rem",
        "list-gap-icon-to-label": "0.25rem",
        "input-height-extra-small": "0.125rem",
        "input-side-l": "0.75rem",
        "input-gap-label-to-input": "0.25rem",
        "input-gap-text-area-controls": "0.5rem",
        "list-height-item": "0.5rem",
        "list-height-actions": "0.25rem",
        "list-height-title-top": "0.75rem",
        "list-side-item": "1rem",
        "list-side-actions": "1rem",
        "list-height-bottom": "8rem",
        "list-gap-checkbox-to-label": "0.5rem",
        "list-gap-label-to-subcontent": "0.0625rem",
        "list-side-extra-actions": "1.5rem",
        "list-height-extra-actions": "1.5rem",
        "modal-side-desktop": "2.5rem",
        "modal-height-desktop": "2.5rem",
        "modal-gap-buttons": "1rem",
        "modal-gap-text": "0.625rem",
        "modal-gap-content": "1.75rem",
        "modal-gap-form": "2rem",
        "toast-height-content": "0.875rem",
        "toast-side-default": "1rem",
        "toast-gap-action": "1rem",
        "tooltip-height-default": "0.5rem",
        "tooltip-side-default": "0.75rem",
        "table-cell-content-gap-s": "0.25rem",
        "table-cell-content-gap-m": "0.375rem",
        "table-cell-content-gap-l": "0.5rem",
        "table-cell-content-height-s": "0.25rem",
        "table-cell-content-height-m": "0.25rem",
        "table-cell-content-side-s": "0.375rem",
        "table-cell-content-side-m": "0.5rem",
        "table-cell-container-height-default": "0.5rem",
        "table-cell-container-side-default": "0.5rem",
        "table-header-cell-container-height-default": "0.5rem",
        "table-header-cell-container-side-default": "0.5rem",
        "toast-height-actions-mobile": "0.5rem",
        "toast-gap-icon-to-text": "0.75rem",
        "alert-height-content": "0.875rem",
        "alert-height-actions-mobile": "0.5rem",
        "alert-side-default": "1rem",
        "alert-gap-icon-to-text": "0.75rem",
        "alert-gap-action": "1rem",
        "slider-side-bar": "0rem",
        "slider-height-bar": "0.625rem",
        "input-gap-error-to-input": "0.375rem",
        "list-side-title": "1rem",
        "list-gap-title-to-icon": "0.125rem",
        "list-gap-title-to-helper-text": "0rem",
        "list-height-title-bottom": "0.375rem",
        "toast-height-actions-desktop": "0.75rem",
        "alert-height-actions-desktop": "0.75rem",
        "tooltip-gap-margin": "0.75rem",
        "list-gap-margin": "1rem",
        "modal-gap-buttons-top": "0.25rem",
        "list-height-subcontent-bottom": "0.25rem",
        "pill-side-default": "0.5rem",
        "pill-height-default": "0.125rem",
        "button-focus-rounding-xs": "0.125rem",
        "modal-side-mobile": "1rem",
        "modal-height-mobile": "1rem",
        "pill-gap-pill-to-pill": "0.5rem",
        "progress-side-bar": "0.5rem",
        "progress-height-bar": "0.25rem",
        "file-upload-container-height-top-bottom": "1.5rem",
        "file-upload-container-side-default": "1.5rem",
        "file-upload-file-card-height-top-bottom": "1rem",
        "file-upload-file-card-side-default": "1rem",
        "file-upload-content-height-xs": "0.25rem",
        "file-upload-content-height-s": "0.5rem",
        "file-upload-content-height-m": "1rem",
        "file-upload-content-height-l": "1.75rem",
        "file-upload-content-height-xl": "2rem",
        "input-gap-trailing-elements": "0.25rem",
        "toast-gap-margin-desktop": "2rem",
        "toast-gap-margin-mobile": "1rem",
        "list-gap-content": "0.375rem",
        "floating-label-input-height-empty": "1rem",
        "floating-label-input-height-filled": "0.5rem",
        "floating-label-input-gap-label-to-input": "0.25rem",
        "floating-label-input-gap-trailing-elements": "0.25rem",
        "floating-label-input-gap-error-to-input": "0.375rem",
        "file-upload-content-gap-icon-to-content": "0.5rem",
        "file-upload-content-gap-text-to-text": "0.25rem",
        "file-upload-content-gap-content-to-button": "1.25rem",
        "file-upload-content-gap-text-to-progress": "0.25rem",
        "file-upload-content-gap-progress-actions": "0.5rem",
        "file-upload-content-gap-left-to-right-content": "1rem",
        "file-upload-content-gap-button-to-button": "1rem",
        "file-upload-file-card-gap-icon-to-content-gap": "0.5rem",
        "file-upload-file-card-gap-text-to-text-gap": "0.25rem",
        "file-upload-file-card-gap-progress-actions-gap": "0.5rem",
        "file-upload-file-card-gap-left-to-right-content-gap": "1rem",
        "file-upload-file-card-gap-trailing-actions": "0.5rem",
        "file-upload-input-gap-input-to-button-gap": "0.625rem",
        "image-upload-content-gap-icon-to-content-gap": "0.5rem",
        "image-upload-avatar-with-buttons-height-top-bottom": "0rem",
        "image-upload-avatar-with-buttons-side-default": "0rem",
        "image-upload-avatar-with-buttons-gap-avatar-to-content-gap": "1.25rem",
        "image-upload-avatar-with-buttons-gap-text-to-text-gap": "0.25rem",
        "image-upload-avatar-with-buttons-gap-text-to-buttons-gap": "1.25rem",
        "image-upload-avatar-with-buttons-gap-actions-gap": "1rem",
        "segmented-control-height-segment": "0.25rem",
        "segmented-control-side-segment": "0.75rem",
        "segmented-control-gap-content-icon-to-text": "0.25rem",
        "segmented-control-gap-segment-to-segment": "0.125rem",
        "image-overlay-inside-rounding-none": "0rem",
        "image-overlay-inside-rounding-rounded": "1rem",
        "segmented-control-side-content": "0.375rem",
        "segmented-control-side-segmented-control": "0.125rem",
        "image-overlay-outside-rounding-none": "0rem",
        "image-overlay-outside-rounding-rounded": "1rem",
        "input-gap-leading-elements": "0.375rem",
        "image-upload-avatar-with-buttons-gap-icon-button-right-bottom": "0rem",
        "image-upload-container-gap-icon-button-right-bottom": "0rem",
        "modal-gap-desktop-modal-close-icon-top-right": "0.25rem",
        "modal-gap-mobile-modal-close-icon-top-right": "0rem",
        "modal-gap-close-icon-container": "0.5rem",
        "list-gap-nav-button-icon-to-label": "0.125rem",
        "list-gap-footer-button-icon-to-label": "0.125rem",
        "button-height-xs": "0.125rem",
        "button-side-xs": "0.125rem",
        "input-gap-header-text-to-elements": "0.125rem",
        "floating-label-input-gap-header-text-to-elements": "0.125rem",
        "floating-label-input-gap-leading-elements": "0.375rem",
        "input-gap-input-text-to-elements": "0.5rem",
        "input-gap-text-to-text": "0.25rem",
        "avatar-padding-xs": "0.25rem",
        "avatar-padding-s": "0.5rem",
        "avatar-padding-m": "0.625rem",
        "avatar-padding-l": "1rem",
        "avatar-padding-xl": "1.25rem",
        "avatar-padding-xxl": "1.75rem",
        "progress-height-leading-and-trailing": "0.25rem",
        "progress-side-leading-and-trailing": "0.5rem",
        "slider-height-leading-and-trailing": "0.625rem",
        "slider-side-leading-and-trailing": "0rem",
        "button-height-none": "0rem",
        "button-side-none": "0rem",
        "button-rounding-none": "0rem",
        "input-height-small": "0.25rem",
        "input-height-default": "0.625rem",
        "input-height-large": "1rem",
        "pagination-button-to-button": "0.5rem",
        "button-button-content-side-none": "0rem",
        "button-button-content-side-default": "0.375rem",
        "button-button-content-height-none": "0rem",
        "button-side-sm": "0.5rem",
        "button-side-ml": "1rem",
        "input-side-xs": "0.25rem",
        "input-side-s": "0.375rem",
        "input-side-m": "0.625rem",
        "button-side-xxs": "0.125rem",
        "button-segment-control-buttonside-xs": "0.875rem",
        "button-segment-control-buttonside-s": "1.25rem",
        "button-segment-control-buttonside-m": "2rem",
        "button-segment-control-buttonside-l": "4rem",
        "button-segment-control-segment-side-xs": "0.125rem",
        "button-segment-control-segment-side-s": "0.25rem",
        "button-segment-control-segment-side-m": "0.375rem",
        "button-segment-control-segment-side-l": "0.375rem",
        "button-segment-control-segment-height-xs": "0.125rem",
        "button-segment-control-segment-height-s": "0.25rem",
        "button-segment-control-segment-height-m": "0.375rem",
        "button-segment-control-segment-height-l": "0.375rem",
        "button-gap-icon-to-label": "0.25rem",
      },
      spacing: {
        "0": "0rem",
        "1": "0.25rem",
        "2": "0.5rem",
        "3": "0.75rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "7": "1.75rem",
        "8": "2rem",
        "9": "2.25rem",
        "10": "2.5rem",
        "11": "2.75rem",
        "12": "3rem",
        "14": "3.5rem",
        "16": "4rem",
        "18": "4.5rem",
        "20": "5rem",
        "24": "6rem",
        "28": "7rem",
        "32": "8rem",
        "36": "9rem",
        "40": "10rem",
        "44": "11rem",
        "48": "12rem",
        "52": "13rem",
        "56": "14rem",
        "60": "15rem",
        "64": "16rem",
        "72": "18rem",
        "80": "20rem",
        "96": "24rem",
        px: "0.0625rem",
        "0-5": "0.125rem",
        "1-5": "0.375rem",
        "2-5": "0.625rem",
        "3-5": "0.875rem",
        "avatar-height-xs": "1.5rem",
        "avatar-height-s": "2rem",
        "avatar-height-m": "2.5rem",
        "avatar-height-l": "3.5rem",
        "avatar-height-xl": "4.5rem",
        "avatar-height-xxl": "6rem",
        "button-width-min-width-xxs": "1.625rem",
        "button-width-min-width-xs": "1.875rem",
        "button-width-min-width-s": "2.125rem",
        "button-width-min-width-m": "2.875rem",
        "button-width-min-width-l": "3.625rem",
        "global-side-xs": "0.125rem",
        "global-side-s": "0.25rem",
        "global-side-m": "0.625rem",
        "global-side-l": "1rem",
        "global-side-xl": "1.25rem",
        "global-gap-xs": "0.25rem",
        "global-gap-s": "0.5rem",
        "global-gap-m": "0.75rem",
        "global-gap-l": "1rem",
        "global-gap-xl": "1.25rem",
        "global-gap-ml": "0.875rem",
        "global-gap-sm": "0.625rem",
        "global-side-sm": "0.375rem",
        "global-side-ml": "0.75rem",
        "global-height-xs": "0.125rem",
        "global-height-s": "0.25rem",
        "global-height-m": "0.625rem",
        "global-height-l": "0.875rem",
        "global-height-xl": "1rem",
        "button-height-s": "0.25rem",
        "button-height-m": "0.625rem",
        "button-height-l": "1rem",
        "button-side-s": "0.25rem",
        "button-side-m": "1rem",
        "button-side-l": "1.75rem",
        "list-gap-icon-to-label": "0.25rem",
        "input-height-extra-small": "0.125rem",
        "input-side-l": "0.75rem",
        "input-gap-label-to-input": "0.25rem",
        "input-gap-text-area-controls": "0.5rem",
        "list-height-item": "0.5rem",
        "list-height-actions": "0.25rem",
        "list-height-title-top": "0.75rem",
        "list-side-item": "1rem",
        "list-side-actions": "1rem",
        "list-height-bottom": "8rem",
        "list-gap-checkbox-to-label": "0.5rem",
        "list-gap-label-to-subcontent": "0.0625rem",
        "list-side-extra-actions": "1.5rem",
        "list-height-extra-actions": "1.5rem",
        "modal-side-desktop": "2.5rem",
        "modal-height-desktop": "2.5rem",
        "modal-gap-buttons": "1rem",
        "modal-gap-text": "0.625rem",
        "modal-gap-content": "1.75rem",
        "modal-gap-form": "2rem",
        "toast-height-content": "0.875rem",
        "toast-side-default": "1rem",
        "toast-gap-action": "1rem",
        "tooltip-height-default": "0.5rem",
        "tooltip-side-default": "0.75rem",
        "table-cell-content-gap-s": "0.25rem",
        "table-cell-content-gap-m": "0.375rem",
        "table-cell-content-gap-l": "0.5rem",
        "table-cell-content-height-s": "0.25rem",
        "table-cell-content-height-m": "0.25rem",
        "table-cell-content-side-s": "0.375rem",
        "table-cell-content-side-m": "0.5rem",
        "table-cell-container-height-default": "0.5rem",
        "table-cell-container-side-default": "0.5rem",
        "table-header-cell-container-height-default": "0.5rem",
        "table-header-cell-container-side-default": "0.5rem",
        "toast-height-actions-mobile": "0.5rem",
        "toast-gap-icon-to-text": "0.75rem",
        "alert-height-content": "0.875rem",
        "alert-height-actions-mobile": "0.5rem",
        "alert-side-default": "1rem",
        "alert-gap-icon-to-text": "0.75rem",
        "alert-gap-action": "1rem",
        "slider-side-bar": "0rem",
        "slider-height-bar": "0.625rem",
        "input-gap-error-to-input": "0.375rem",
        "list-side-title": "1rem",
        "list-gap-title-to-icon": "0.125rem",
        "list-gap-title-to-helper-text": "0rem",
        "list-height-title-bottom": "0.375rem",
        "toast-height-actions-desktop": "0.75rem",
        "alert-height-actions-desktop": "0.75rem",
        "tooltip-gap-margin": "0.75rem",
        "list-gap-margin": "1rem",
        "modal-gap-buttons-top": "0.25rem",
        "list-height-subcontent-bottom": "0.25rem",
        "pill-side-default": "0.5rem",
        "pill-height-default": "0.125rem",
        "button-focus-rounding-xs": "0.125rem",
        "modal-side-mobile": "1rem",
        "modal-height-mobile": "1rem",
        "pill-gap-pill-to-pill": "0.5rem",
        "progress-side-bar": "0.5rem",
        "progress-height-bar": "0.25rem",
        "file-upload-container-height-top-bottom": "1.5rem",
        "file-upload-container-side-default": "1.5rem",
        "file-upload-file-card-height-top-bottom": "1rem",
        "file-upload-file-card-side-default": "1rem",
        "file-upload-content-height-xs": "0.25rem",
        "file-upload-content-height-s": "0.5rem",
        "file-upload-content-height-m": "1rem",
        "file-upload-content-height-l": "1.75rem",
        "file-upload-content-height-xl": "2rem",
        "input-gap-trailing-elements": "0.25rem",
        "toast-gap-margin-desktop": "2rem",
        "toast-gap-margin-mobile": "1rem",
        "list-gap-content": "0.375rem",
        "floating-label-input-height-empty": "1rem",
        "floating-label-input-height-filled": "0.5rem",
        "floating-label-input-gap-label-to-input": "0.25rem",
        "floating-label-input-gap-trailing-elements": "0.25rem",
        "floating-label-input-gap-error-to-input": "0.375rem",
        "file-upload-content-gap-icon-to-content": "0.5rem",
        "file-upload-content-gap-text-to-text": "0.25rem",
        "file-upload-content-gap-content-to-button": "1.25rem",
        "file-upload-content-gap-text-to-progress": "0.25rem",
        "file-upload-content-gap-progress-actions": "0.5rem",
        "file-upload-content-gap-left-to-right-content": "1rem",
        "file-upload-content-gap-button-to-button": "1rem",
        "file-upload-file-card-gap-icon-to-content-gap": "0.5rem",
        "file-upload-file-card-gap-text-to-text-gap": "0.25rem",
        "file-upload-file-card-gap-progress-actions-gap": "0.5rem",
        "file-upload-file-card-gap-left-to-right-content-gap": "1rem",
        "file-upload-file-card-gap-trailing-actions": "0.5rem",
        "file-upload-input-gap-input-to-button-gap": "0.625rem",
        "image-upload-content-gap-icon-to-content-gap": "0.5rem",
        "image-upload-avatar-with-buttons-height-top-bottom": "0rem",
        "image-upload-avatar-with-buttons-side-default": "0rem",
        "image-upload-avatar-with-buttons-gap-avatar-to-content-gap": "1.25rem",
        "image-upload-avatar-with-buttons-gap-text-to-text-gap": "0.25rem",
        "image-upload-avatar-with-buttons-gap-text-to-buttons-gap": "1.25rem",
        "image-upload-avatar-with-buttons-gap-actions-gap": "1rem",
        "segmented-control-height-segment": "0.25rem",
        "segmented-control-side-segment": "0.75rem",
        "segmented-control-gap-content-icon-to-text": "0.25rem",
        "segmented-control-gap-segment-to-segment": "0.125rem",
        "image-overlay-inside-rounding-none": "0rem",
        "image-overlay-inside-rounding-rounded": "1rem",
        "segmented-control-side-content": "0.375rem",
        "segmented-control-side-segmented-control": "0.125rem",
        "image-overlay-outside-rounding-none": "0rem",
        "image-overlay-outside-rounding-rounded": "1rem",
        "input-gap-leading-elements": "0.375rem",
        "image-upload-avatar-with-buttons-gap-icon-button-right-bottom": "0rem",
        "image-upload-container-gap-icon-button-right-bottom": "0rem",
        "modal-gap-desktop-modal-close-icon-top-right": "0.25rem",
        "modal-gap-mobile-modal-close-icon-top-right": "0rem",
        "modal-gap-close-icon-container": "0.5rem",
        "list-gap-nav-button-icon-to-label": "0.125rem",
        "list-gap-footer-button-icon-to-label": "0.125rem",
        "button-height-xs": "0.125rem",
        "button-side-xs": "0.125rem",
        "input-gap-header-text-to-elements": "0.125rem",
        "floating-label-input-gap-header-text-to-elements": "0.125rem",
        "floating-label-input-gap-leading-elements": "0.375rem",
        "input-gap-input-text-to-elements": "0.5rem",
        "input-gap-text-to-text": "0.25rem",
        "avatar-padding-xs": "0.25rem",
        "avatar-padding-s": "0.5rem",
        "avatar-padding-m": "0.625rem",
        "avatar-padding-l": "1rem",
        "avatar-padding-xl": "1.25rem",
        "avatar-padding-xxl": "1.75rem",
        "progress-height-leading-and-trailing": "0.25rem",
        "progress-side-leading-and-trailing": "0.5rem",
        "slider-height-leading-and-trailing": "0.625rem",
        "slider-side-leading-and-trailing": "0rem",
        "button-height-none": "0rem",
        "button-side-none": "0rem",
        "button-rounding-none": "0rem",
        "input-height-small": "0.25rem",
        "input-height-default": "0.625rem",
        "input-height-large": "1rem",
        "pagination-button-to-button": "0.5rem",
        "button-button-content-side-none": "0rem",
        "button-button-content-side-default": "0.375rem",
        "button-button-content-height-none": "0rem",
        "button-side-sm": "0.5rem",
        "button-side-ml": "1rem",
        "input-side-xs": "0.25rem",
        "input-side-s": "0.375rem",
        "input-side-m": "0.625rem",
        "button-side-xxs": "0.125rem",
        "button-segment-control-buttonside-xs": "0.875rem",
        "button-segment-control-buttonside-s": "1.25rem",
        "button-segment-control-buttonside-m": "2rem",
        "button-segment-control-buttonside-l": "4rem",
        "button-segment-control-segment-side-xs": "0.125rem",
        "button-segment-control-segment-side-s": "0.25rem",
        "button-segment-control-segment-side-m": "0.375rem",
        "button-segment-control-segment-side-l": "0.375rem",
        "button-segment-control-segment-height-xs": "0.125rem",
        "button-segment-control-segment-height-s": "0.25rem",
        "button-segment-control-segment-height-m": "0.375rem",
        "button-segment-control-segment-height-l": "0.375rem",
        "button-gap-icon-to-label": "0.25rem",
      },
      boxShadow: {
        "1": "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
        "2": "0 1px 3px 0 rgba(0, 0, 0, 0.10), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
        "3": "0 4px 6px -1px rgba(0, 0, 0, 0.10), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
        "4": "0 10px 15px -3px rgba(0, 0, 0, 0.10), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
        "5": "0 20px 25px -5px rgba(0, 0, 0, 0.10), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
        "6": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
        "text-shadow-dark-mode": "0 2px 6px 0 rgba(0, 0, 0, 0.30)",
        inner: "0 2px 4px 0 rgba(0, 0, 0, 0.06) inset",
      },
      blur: {
        "0": "0px",
        "1": "2px",
        "2": "4px",
        "3": "6px",
        "4": "8px",
        "5": "12px",
        "6": "20px",
        "7": "32px",
      },
      backdropBlur: {
        "1": "2px",
        "2": "4px",
        "3": "6px",
        "4": "8px",
        "5": "12px",
        "6": "20px",
        "7": "32px",
      },
      fontSize: {
        "desktop-headline-1": [
          "3.5rem",
          {
            lineHeight: "1.2857",
            letterSpacing: "0em",
          },
        ],
        "desktop-title-1": [
          "3rem",
          {
            lineHeight: "1.25",
            letterSpacing: "0em",
          },
        ],
        "desktop-title-2": [
          "2rem",
          {
            lineHeight: "1.3125",
            letterSpacing: "0em",
          },
        ],
        "desktop-title-3": [
          "1.75rem",
          {
            lineHeight: "1.3571",
            letterSpacing: "0em",
          },
        ],
        "desktop-title-4": [
          "1.375rem",
          {
            lineHeight: "1.2727",
            letterSpacing: "0em",
          },
        ],
        "desktop-title-5": [
          "1.125rem",
          {
            lineHeight: "1.4444",
            letterSpacing: "0em",
          },
        ],
        "desktop-title-6": [
          "1rem",
          {
            lineHeight: "1.5",
            letterSpacing: "0em",
          },
        ],
        "mobile-headline-1": [
          "2rem",
          {
            lineHeight: "1.1875",
            letterSpacing: "0em",
          },
        ],
        "mobile-title-1": [
          "1.75rem",
          {
            lineHeight: "1.2857",
            letterSpacing: "0em",
          },
        ],
        "mobile-title-2": [
          "1.5rem",
          {
            lineHeight: "1.3333",
            letterSpacing: "0em",
          },
        ],
        "mobile-title-3": [
          "1.125rem",
          {
            lineHeight: "1.4444",
            letterSpacing: "0em",
          },
        ],
        "mobile-title-4": [
          "1rem",
          {
            lineHeight: "1.5",
            letterSpacing: "0em",
          },
        ],
        "mobile-title-5": [
          "0.875rem",
          {
            lineHeight: "1.2857",
            letterSpacing: "0em",
          },
        ],
        "mobile-title-6": [
          "0.875rem",
          {
            lineHeight: "1.2857",
            letterSpacing: "0em",
          },
        ],
        "desktop-body-1": [
          "1.25rem",
          {
            lineHeight: "1.8",
            letterSpacing: "0em",
          },
        ],
        "desktop-body-2": [
          "1.125rem",
          {
            lineHeight: "1.7778",
            letterSpacing: "-0.0018em",
          },
        ],
        "desktop-body-3": [
          "1rem",
          {
            lineHeight: "1.75",
            letterSpacing: "-0.0016em",
          },
        ],
        "desktop-body-4": [
          "0.875rem",
          {
            lineHeight: "1.7143",
            letterSpacing: "-0.0014em",
          },
        ],
        "mobile-body-1": [
          "1.125rem",
          {
            lineHeight: "1.5556",
            letterSpacing: "0em",
          },
        ],
        "mobile-body-2": [
          "1rem",
          {
            lineHeight: "1.75",
            letterSpacing: "-0.0016em",
          },
        ],
        "mobile-body-3": [
          "0.9375rem",
          {
            lineHeight: "1.7333",
            letterSpacing: "-0.0015em",
          },
        ],
        "mobile-body-4": [
          "0.875rem",
          {
            lineHeight: "1.7143",
            letterSpacing: "-0.0014em",
          },
        ],
        "label-1": [
          "1rem",
          {
            lineHeight: "1.5",
            letterSpacing: "0em",
          },
        ],
        "label-2": [
          "0.875rem",
          {
            lineHeight: "1.7143",
            letterSpacing: "0em",
          },
        ],
        "label-3": [
          "0.75rem",
          {
            lineHeight: "1.3333",
            letterSpacing: "-0.0012em",
          },
        ],
      },
      fontFamily: {
        secondary: ["var(--font-geist-base)", ...fontFamily.sans],
        geist: ["var(--font-geist-base)", ...fontFamily.sans],
        primary: ["var(--font-inter-base)", ...fontFamily.sans],
        inter: ["var(--font-inter-base)", ...fontFamily.sans],
      },
      fontWeight: {
        "headings-default": "500",
        "headings-prominent-1": "600",
        "body-default": "400",
        "body-prominent-1": "500",
        "body-prominent-2": "600",
        "labels-default": "500",
        "labels-prominent-1": "600",
      },
      backgroundImage: {},
    },
  },
};

export default config;
