/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as CodeExamplesRouteRouteImport } from './pages/code-examples/route'
import { Route as publicOnlyRouteRouteImport } from './pages/(public-only)/route'
import { Route as privateRouteRouteImport } from './pages/(private)/route'
import { Route as CodeExamplesIndexRouteImport } from './pages/code-examples/index'
import { Route as privateIndexRouteImport } from './pages/(private)/index'
import { Route as CodeExamplesToastsRouteImport } from './pages/code-examples/toasts'
import { Route as CodeExamplesTextRouteImport } from './pages/code-examples/text'
import { Route as CodeExamplesTableRouteImport } from './pages/code-examples/table'
import { Route as CodeExamplesModalsRouteImport } from './pages/code-examples/modals'
import { Route as CodeExamplesInputsRouteImport } from './pages/code-examples/inputs'
import { Route as CodeExamplesFormsRouteImport } from './pages/code-examples/forms'
import { Route as CodeExamplesButtonsRouteImport } from './pages/code-examples/buttons'
import { Route as publicOnlyLoginRouteImport } from './pages/(public-only)/login'

const CodeExamplesRouteRoute = CodeExamplesRouteRouteImport.update({
  id: '/code-examples',
  path: '/code-examples',
  getParentRoute: () => rootRouteImport,
} as any)
const publicOnlyRouteRoute = publicOnlyRouteRouteImport.update({
  id: '/(public-only)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeExamplesIndexRoute = CodeExamplesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CodeExamplesRouteRoute,
} as any)
const privateIndexRoute = privateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateRouteRoute,
} as any)
const CodeExamplesToastsRoute = CodeExamplesToastsRouteImport.update({
  id: '/toasts',
  path: '/toasts',
  getParentRoute: () => CodeExamplesRouteRoute,
} as any)
const CodeExamplesTextRoute = CodeExamplesTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => CodeExamplesRouteRoute,
} as any)
const CodeExamplesTableRoute = CodeExamplesTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => CodeExamplesRouteRoute,
} as any)
const CodeExamplesModalsRoute = CodeExamplesModalsRouteImport.update({
  id: '/modals',
  path: '/modals',
  getParentRoute: () => CodeExamplesRouteRoute,
} as any)
const CodeExamplesInputsRoute = CodeExamplesInputsRouteImport.update({
  id: '/inputs',
  path: '/inputs',
  getParentRoute: () => CodeExamplesRouteRoute,
} as any)
const CodeExamplesFormsRoute = CodeExamplesFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => CodeExamplesRouteRoute,
} as any)
const CodeExamplesButtonsRoute = CodeExamplesButtonsRouteImport.update({
  id: '/buttons',
  path: '/buttons',
  getParentRoute: () => CodeExamplesRouteRoute,
} as any)
const publicOnlyLoginRoute = publicOnlyLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicOnlyRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/code-examples': typeof CodeExamplesRouteRouteWithChildren
  '/login': typeof publicOnlyLoginRoute
  '/code-examples/buttons': typeof CodeExamplesButtonsRoute
  '/code-examples/forms': typeof CodeExamplesFormsRoute
  '/code-examples/inputs': typeof CodeExamplesInputsRoute
  '/code-examples/modals': typeof CodeExamplesModalsRoute
  '/code-examples/table': typeof CodeExamplesTableRoute
  '/code-examples/text': typeof CodeExamplesTextRoute
  '/code-examples/toasts': typeof CodeExamplesToastsRoute
  '/': typeof privateIndexRoute
  '/code-examples/': typeof CodeExamplesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof publicOnlyLoginRoute
  '/code-examples/buttons': typeof CodeExamplesButtonsRoute
  '/code-examples/forms': typeof CodeExamplesFormsRoute
  '/code-examples/inputs': typeof CodeExamplesInputsRoute
  '/code-examples/modals': typeof CodeExamplesModalsRoute
  '/code-examples/table': typeof CodeExamplesTableRoute
  '/code-examples/text': typeof CodeExamplesTextRoute
  '/code-examples/toasts': typeof CodeExamplesToastsRoute
  '/': typeof privateIndexRoute
  '/code-examples': typeof CodeExamplesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateRouteRouteWithChildren
  '/(public-only)': typeof publicOnlyRouteRouteWithChildren
  '/code-examples': typeof CodeExamplesRouteRouteWithChildren
  '/(public-only)/login': typeof publicOnlyLoginRoute
  '/code-examples/buttons': typeof CodeExamplesButtonsRoute
  '/code-examples/forms': typeof CodeExamplesFormsRoute
  '/code-examples/inputs': typeof CodeExamplesInputsRoute
  '/code-examples/modals': typeof CodeExamplesModalsRoute
  '/code-examples/table': typeof CodeExamplesTableRoute
  '/code-examples/text': typeof CodeExamplesTextRoute
  '/code-examples/toasts': typeof CodeExamplesToastsRoute
  '/(private)/': typeof privateIndexRoute
  '/code-examples/': typeof CodeExamplesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/code-examples'
    | '/login'
    | '/code-examples/buttons'
    | '/code-examples/forms'
    | '/code-examples/inputs'
    | '/code-examples/modals'
    | '/code-examples/table'
    | '/code-examples/text'
    | '/code-examples/toasts'
    | '/'
    | '/code-examples/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/code-examples/buttons'
    | '/code-examples/forms'
    | '/code-examples/inputs'
    | '/code-examples/modals'
    | '/code-examples/table'
    | '/code-examples/text'
    | '/code-examples/toasts'
    | '/'
    | '/code-examples'
  id:
    | '__root__'
    | '/(private)'
    | '/(public-only)'
    | '/code-examples'
    | '/(public-only)/login'
    | '/code-examples/buttons'
    | '/code-examples/forms'
    | '/code-examples/inputs'
    | '/code-examples/modals'
    | '/code-examples/table'
    | '/code-examples/text'
    | '/code-examples/toasts'
    | '/(private)/'
    | '/code-examples/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicOnlyRouteRoute: typeof publicOnlyRouteRouteWithChildren
  CodeExamplesRouteRoute: typeof CodeExamplesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/code-examples': {
      id: '/code-examples'
      path: '/code-examples'
      fullPath: '/code-examples'
      preLoaderRoute: typeof CodeExamplesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public-only)': {
      id: '/(public-only)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicOnlyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-examples/': {
      id: '/code-examples/'
      path: '/'
      fullPath: '/code-examples/'
      preLoaderRoute: typeof CodeExamplesIndexRouteImport
      parentRoute: typeof CodeExamplesRouteRoute
    }
    '/(private)/': {
      id: '/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/code-examples/toasts': {
      id: '/code-examples/toasts'
      path: '/toasts'
      fullPath: '/code-examples/toasts'
      preLoaderRoute: typeof CodeExamplesToastsRouteImport
      parentRoute: typeof CodeExamplesRouteRoute
    }
    '/code-examples/text': {
      id: '/code-examples/text'
      path: '/text'
      fullPath: '/code-examples/text'
      preLoaderRoute: typeof CodeExamplesTextRouteImport
      parentRoute: typeof CodeExamplesRouteRoute
    }
    '/code-examples/table': {
      id: '/code-examples/table'
      path: '/table'
      fullPath: '/code-examples/table'
      preLoaderRoute: typeof CodeExamplesTableRouteImport
      parentRoute: typeof CodeExamplesRouteRoute
    }
    '/code-examples/modals': {
      id: '/code-examples/modals'
      path: '/modals'
      fullPath: '/code-examples/modals'
      preLoaderRoute: typeof CodeExamplesModalsRouteImport
      parentRoute: typeof CodeExamplesRouteRoute
    }
    '/code-examples/inputs': {
      id: '/code-examples/inputs'
      path: '/inputs'
      fullPath: '/code-examples/inputs'
      preLoaderRoute: typeof CodeExamplesInputsRouteImport
      parentRoute: typeof CodeExamplesRouteRoute
    }
    '/code-examples/forms': {
      id: '/code-examples/forms'
      path: '/forms'
      fullPath: '/code-examples/forms'
      preLoaderRoute: typeof CodeExamplesFormsRouteImport
      parentRoute: typeof CodeExamplesRouteRoute
    }
    '/code-examples/buttons': {
      id: '/code-examples/buttons'
      path: '/buttons'
      fullPath: '/code-examples/buttons'
      preLoaderRoute: typeof CodeExamplesButtonsRouteImport
      parentRoute: typeof CodeExamplesRouteRoute
    }
    '/(public-only)/login': {
      id: '/(public-only)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicOnlyLoginRouteImport
      parentRoute: typeof publicOnlyRouteRoute
    }
  }
}

interface privateRouteRouteChildren {
  privateIndexRoute: typeof privateIndexRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateIndexRoute: privateIndexRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

interface publicOnlyRouteRouteChildren {
  publicOnlyLoginRoute: typeof publicOnlyLoginRoute
}

const publicOnlyRouteRouteChildren: publicOnlyRouteRouteChildren = {
  publicOnlyLoginRoute: publicOnlyLoginRoute,
}

const publicOnlyRouteRouteWithChildren = publicOnlyRouteRoute._addFileChildren(
  publicOnlyRouteRouteChildren,
)

interface CodeExamplesRouteRouteChildren {
  CodeExamplesButtonsRoute: typeof CodeExamplesButtonsRoute
  CodeExamplesFormsRoute: typeof CodeExamplesFormsRoute
  CodeExamplesInputsRoute: typeof CodeExamplesInputsRoute
  CodeExamplesModalsRoute: typeof CodeExamplesModalsRoute
  CodeExamplesTableRoute: typeof CodeExamplesTableRoute
  CodeExamplesTextRoute: typeof CodeExamplesTextRoute
  CodeExamplesToastsRoute: typeof CodeExamplesToastsRoute
  CodeExamplesIndexRoute: typeof CodeExamplesIndexRoute
}

const CodeExamplesRouteRouteChildren: CodeExamplesRouteRouteChildren = {
  CodeExamplesButtonsRoute: CodeExamplesButtonsRoute,
  CodeExamplesFormsRoute: CodeExamplesFormsRoute,
  CodeExamplesInputsRoute: CodeExamplesInputsRoute,
  CodeExamplesModalsRoute: CodeExamplesModalsRoute,
  CodeExamplesTableRoute: CodeExamplesTableRoute,
  CodeExamplesTextRoute: CodeExamplesTextRoute,
  CodeExamplesToastsRoute: CodeExamplesToastsRoute,
  CodeExamplesIndexRoute: CodeExamplesIndexRoute,
}

const CodeExamplesRouteRouteWithChildren =
  CodeExamplesRouteRoute._addFileChildren(CodeExamplesRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  privateRouteRoute: privateRouteRouteWithChildren,
  publicOnlyRouteRoute: publicOnlyRouteRouteWithChildren,
  CodeExamplesRouteRoute: CodeExamplesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
